#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("fft_in_0_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("fft_in_0_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("fft_in_0_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("fft_in_0_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("fft_in_0_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("fft_in_0_TLAST", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("fft_in_1_TDATA", 32, hls_in, 4, "axis", "in_data", 1),
	Port_Property("fft_in_1_TVALID", 1, hls_in, 7, "axis", "in_vld", 1),
	Port_Property("fft_in_1_TREADY", 1, hls_out, 7, "axis", "in_acc", 1),
	Port_Property("fft_in_1_TKEEP", 4, hls_in, 5, "axis", "in_data", 1),
	Port_Property("fft_in_1_TSTRB", 4, hls_in, 6, "axis", "in_data", 1),
	Port_Property("fft_in_1_TLAST", 1, hls_in, 7, "axis", "in_data", 1),
	Port_Property("weight_stream_TDATA", 32, hls_in, 8, "axis", "in_data", 1),
	Port_Property("weight_stream_TVALID", 1, hls_in, 11, "axis", "in_vld", 1),
	Port_Property("weight_stream_TREADY", 1, hls_out, 11, "axis", "in_acc", 1),
	Port_Property("weight_stream_TKEEP", 4, hls_in, 9, "axis", "in_data", 1),
	Port_Property("weight_stream_TSTRB", 4, hls_in, 10, "axis", "in_data", 1),
	Port_Property("weight_stream_TLAST", 1, hls_in, 11, "axis", "in_data", 1),
	Port_Property("symbol_num", 4, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("s_axi_SNR_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_SNR_AWADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_SNR_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_SNR_ARADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_SNR_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_SNR_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_SNR_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_SNR_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_SNR_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "snr_monitor_top";
