

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fft_re_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fft_im_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.h_re_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.h_im_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_buf_loop_fu_145"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_buf_loop_fu_145.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_weight_drain_fu_167"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_weight_drain_fu_167.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.DMRS_RE_U"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.DMRS_IM_U"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.mul_16s_15s_30_1_1_U17"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.mul_16s_15s_30_1_1_U18"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.mul_16s_16s_32_1_1_U19"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.mul_16s_16s_32_1_1_U20"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.mac_mulsub_16s_15s_30s_30_4_1_U21"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.mac_muladd_16s_15s_30s_30_4_1_U22"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.mac_muladd_16s_16s_32s_33_4_1_U23"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.mac_muladd_16s_16s_32s_33_4_1_U24"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snr_monitor_top_Pipeline_pilot_snr_fu_181.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.SNR_s_axi_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.udiv_64s_39ns_32_68_seq_1_U38"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_fft_in_0_V_data_V_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_fft_in_0_V_keep_V_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_fft_in_0_V_strb_V_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_fft_in_0_V_last_V_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_fft_in_1_V_data_V_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_fft_in_1_V_keep_V_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_fft_in_1_V_strb_V_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_fft_in_1_V_last_V_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_weight_stream_V_data_V_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_weight_stream_V_keep_V_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_weight_stream_V_strb_V_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_weight_stream_V_last_V_U"}]}
set DependenceCheckSize 0
