#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("fft_in_0_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("fft_in_1_TVALID", 1, hls_in, 7, "axis", "in_vld", 1),
	Port_Property("data_out_0_TREADY", 1, hls_in, 8, "axis", "out_acc", 1),
	Port_Property("data_out_1_TREADY", 1, hls_in, 12, "axis", "out_acc", 1),
	Port_Property("fft_in_0_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("fft_in_0_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("fft_in_0_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("fft_in_0_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("fft_in_0_TLAST", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("fft_in_1_TDATA", 32, hls_in, 4, "axis", "in_data", 1),
	Port_Property("fft_in_1_TREADY", 1, hls_out, 7, "axis", "in_acc", 1),
	Port_Property("fft_in_1_TKEEP", 4, hls_in, 5, "axis", "in_data", 1),
	Port_Property("fft_in_1_TSTRB", 4, hls_in, 6, "axis", "in_data", 1),
	Port_Property("fft_in_1_TLAST", 1, hls_in, 7, "axis", "in_data", 1),
	Port_Property("data_out_0_TDATA", 32, hls_out, 8, "axis", "out_data", 1),
	Port_Property("data_out_0_TVALID", 1, hls_out, 11, "axis", "out_vld", 1),
	Port_Property("data_out_0_TKEEP", 4, hls_out, 9, "axis", "out_data", 1),
	Port_Property("data_out_0_TSTRB", 4, hls_out, 10, "axis", "out_data", 1),
	Port_Property("data_out_0_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("data_out_1_TDATA", 32, hls_out, 12, "axis", "out_data", 1),
	Port_Property("data_out_1_TVALID", 1, hls_out, 15, "axis", "out_vld", 1),
	Port_Property("data_out_1_TKEEP", 4, hls_out, 13, "axis", "out_data", 1),
	Port_Property("data_out_1_TSTRB", 4, hls_out, 14, "axis", "out_data", 1),
	Port_Property("data_out_1_TLAST", 1, hls_out, 15, "axis", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "sc_mapper_rx";
