// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="slot_counter_top_slot_counter_top,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.180000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=125,HLS_SYN_LUT=353,HLS_VERSION=2024_1}" *)

module slot_counter_top (
        ap_clk,
        ap_rst_n,
        symbol_num,
        slot_num,
        gpio_override,
        gpio_symbol_num,
        gpio_slot_num,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [3:0] symbol_num;
output  [6:0] slot_num;
input  [0:0] gpio_override;
input  [3:0] gpio_symbol_num;
input  [6:0] gpio_slot_num;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;

 reg    ap_rst_n_inv;
wire   [0:0] sync_req;
wire   [3:0] sync_symbol;
wire   [6:0] sync_slot;
reg    symbol_num_out_ap_vld;
reg    slot_num_out_ap_vld;
reg   [6:0] slot_cnt;
reg   [11:0] phase_cnt;
reg   [3:0] symbol_cnt;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] gpio_override_read_read_fu_138_p2;
wire   [3:0] add_ln107_fu_262_p2;
wire   [6:0] select_ln103_fu_292_p3;
reg   [6:0] slot_cnt_loc_0_reg_172;
wire   [0:0] sync_req_read_read_fu_120_p2;
wire   [0:0] icmp_ln97_fu_244_p2;
wire   [0:0] icmp_ln100_fu_256_p2;
reg   [3:0] p_0_0_0151_reg_188;
wire   [11:0] add_ln110_fu_306_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln93_fu_214_p2;
wire   [0:0] icmp_ln93_1_fu_220_p2;
wire   [0:0] or_ln93_fu_226_p2;
wire   [11:0] select_ln97_fu_232_p3;
wire   [0:0] icmp_ln103_fu_280_p2;
wire   [6:0] add_ln105_fu_286_p2;
reg   [1:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_condition_104;
reg    ap_condition_110;
reg    ap_condition_113;
reg    ap_condition_107;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 slot_cnt = 7'd0;
#0 phase_cnt = 12'd0;
#0 symbol_cnt = 4'd0;
#0 ap_CS_fsm = 2'd1;
end

slot_counter_top_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .sync_req(sync_req),
    .sync_symbol(sync_symbol),
    .sync_slot(sync_slot),
    .symbol_num_out(p_0_0_0151_reg_188),
    .symbol_num_out_ap_vld(symbol_num_out_ap_vld),
    .slot_num_out(slot_cnt_loc_0_reg_172),
    .slot_num_out_ap_vld(slot_num_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        phase_cnt <= 12'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            if ((sync_req_read_read_fu_120_p2 == 1'd1)) begin
                phase_cnt <= 12'd0;
            end else if (((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd1))) begin
                phase_cnt <= 12'd0;
            end else if ((1'b1 == ap_condition_104)) begin
                phase_cnt <= add_ln110_fu_306_p2;
            end else if ((1'b1 == ap_condition_107)) begin
                phase_cnt <= 12'd0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        slot_cnt <= 7'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            if ((sync_req_read_read_fu_120_p2 == 1'd1)) begin
                slot_cnt <= sync_slot;
            end else if (((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd1))) begin
                slot_cnt <= gpio_slot_num;
            end else if ((1'b1 == ap_condition_110)) begin
                slot_cnt <= select_ln103_fu_292_p3;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        symbol_cnt <= 4'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            if ((sync_req_read_read_fu_120_p2 == 1'd1)) begin
                symbol_cnt <= sync_symbol;
            end else if (((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd1))) begin
                symbol_cnt <= gpio_symbol_num;
            end else if ((1'b1 == ap_condition_110)) begin
                symbol_cnt <= 4'd0;
            end else if ((1'b1 == ap_condition_113)) begin
                symbol_cnt <= add_ln107_fu_262_p2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_113)) begin
            p_0_0_0151_reg_188 <= add_ln107_fu_262_p2;
        end else if ((1'b1 == ap_condition_110)) begin
            p_0_0_0151_reg_188 <= 4'd0;
        end else if ((1'b1 == ap_condition_104)) begin
            p_0_0_0151_reg_188 <= symbol_cnt;
        end else if (((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd1))) begin
            p_0_0_0151_reg_188 <= gpio_symbol_num;
        end else if ((sync_req_read_read_fu_120_p2 == 1'd1)) begin
            p_0_0_0151_reg_188 <= sync_symbol;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln100_fu_256_p2 == 1'd1) & (icmp_ln97_fu_244_p2 == 1'd0))) begin
        slot_cnt_loc_0_reg_172 <= select_ln103_fu_292_p3;
    end else if ((((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln100_fu_256_p2 == 1'd0) & (icmp_ln97_fu_244_p2 == 1'd0)) | ((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln97_fu_244_p2 == 1'd1)))) begin
        slot_cnt_loc_0_reg_172 <= slot_cnt;
    end else if (((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        slot_cnt_loc_0_reg_172 <= gpio_slot_num;
    end else if (((sync_req_read_read_fu_120_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        slot_cnt_loc_0_reg_172 <= sync_slot;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        slot_num_out_ap_vld = 1'b1;
    end else begin
        slot_num_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        symbol_num_out_ap_vld = 1'b1;
    end else begin
        symbol_num_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln105_fu_286_p2 = (slot_cnt + 7'd1);

assign add_ln107_fu_262_p2 = (symbol_cnt + 4'd1);

assign add_ln110_fu_306_p2 = (phase_cnt + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_condition_104 = ((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd0) & (icmp_ln97_fu_244_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_107 = ((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd0) & (icmp_ln97_fu_244_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_110 = ((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd0) & (icmp_ln100_fu_256_p2 == 1'd1) & (icmp_ln97_fu_244_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_113 = ((sync_req_read_read_fu_120_p2 == 1'd0) & (gpio_override_read_read_fu_138_p2 == 1'd0) & (icmp_ln100_fu_256_p2 == 1'd0) & (icmp_ln97_fu_244_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign gpio_override_read_read_fu_138_p2 = gpio_override;

assign icmp_ln100_fu_256_p2 = ((symbol_cnt == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln103_fu_280_p2 = ((slot_cnt == 7'd79) ? 1'b1 : 1'b0);

assign icmp_ln93_1_fu_220_p2 = ((symbol_cnt == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_214_p2 = ((symbol_cnt == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_244_p2 = ((select_ln97_fu_232_p3 > phase_cnt) ? 1'b1 : 1'b0);

assign or_ln93_fu_226_p2 = (icmp_ln93_fu_214_p2 | icmp_ln93_1_fu_220_p2);

assign select_ln103_fu_292_p3 = ((icmp_ln103_fu_280_p2[0:0] == 1'b1) ? 7'd0 : add_ln105_fu_286_p2);

assign select_ln97_fu_232_p3 = ((or_ln93_fu_226_p2[0:0] == 1'b1) ? 12'd2681 : 12'd2677);

assign slot_num = ((gpio_override[0:0] == 1'b1) ? gpio_slot_num : slot_cnt_loc_0_reg_172);

assign symbol_num = ((gpio_override[0:0] == 1'b1) ? gpio_symbol_num : p_0_0_0151_reg_188);

assign sync_req_read_read_fu_120_p2 = sync_req;

endmodule //slot_counter_top
