-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity chan_est_top_chan_est_top_Pipeline_pilot_scan is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pilot_h_im_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pilot_h_im_1_ce0 : OUT STD_LOGIC;
    pilot_h_im_1_we0 : OUT STD_LOGIC;
    pilot_h_im_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    pilot_h_im_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pilot_h_im_ce0 : OUT STD_LOGIC;
    pilot_h_im_we0 : OUT STD_LOGIC;
    pilot_h_im_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    pilot_h_re_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pilot_h_re_1_ce0 : OUT STD_LOGIC;
    pilot_h_re_1_we0 : OUT STD_LOGIC;
    pilot_h_re_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    pilot_h_re_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pilot_h_re_ce0 : OUT STD_LOGIC;
    pilot_h_re_we0 : OUT STD_LOGIC;
    pilot_h_re_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    fft_re_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    fft_re_ce0 : OUT STD_LOGIC;
    fft_re_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    fft_im_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    fft_im_ce0 : OUT STD_LOGIC;
    fft_im_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    fft_re_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    fft_re_1_ce0 : OUT STD_LOGIC;
    fft_re_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    fft_im_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    fft_im_1_ce0 : OUT STD_LOGIC;
    fft_im_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of chan_est_top_chan_est_top_Pipeline_pilot_scan is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_AC : STD_LOGIC_VECTOR (7 downto 0) := "10101100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln246_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal DMRS_RE_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal DMRS_RE_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal DMRS_IM_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal DMRS_IM_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal m_1_reg_405 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln246_fu_225_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln246_reg_416 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln246_reg_416_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln246_reg_416_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln246_reg_416_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal y_im_reg_454 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln46_fu_284_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_1_fu_288_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_1_reg_465 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_3_fu_292_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_3_reg_473 : STD_LOGIC_VECTOR (29 downto 0);
    signal y_im_1_reg_481 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln46_4_fu_296_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln46_1_fu_303_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln46_1_reg_492 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln47_fu_308_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln47_reg_497 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln46_3_fu_316_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln46_3_reg_502 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln47_2_fu_321_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln47_2_reg_507 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln249_fu_276_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_fu_66 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln246_fu_214_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_m_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal DMRS_RE_ce0_local : STD_LOGIC;
    signal DMRS_IM_ce0_local : STD_LOGIC;
    signal fft_re_ce0_local : STD_LOGIC;
    signal fft_im_ce0_local : STD_LOGIC;
    signal fft_re_1_ce0_local : STD_LOGIC;
    signal fft_im_1_ce0_local : STD_LOGIC;
    signal pilot_h_re_we0_local : STD_LOGIC;
    signal pilot_h_re_ce0_local : STD_LOGIC;
    signal pilot_h_re_1_we0_local : STD_LOGIC;
    signal pilot_h_re_1_ce0_local : STD_LOGIC;
    signal pilot_h_im_we0_local : STD_LOGIC;
    signal pilot_h_im_ce0_local : STD_LOGIC;
    signal pilot_h_im_1_we0_local : STD_LOGIC;
    signal pilot_h_im_1_ce0_local : STD_LOGIC;
    signal trunc_ln248_fu_230_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_241_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_fu_233_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln248_fu_248_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln248_fu_252_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_fu_258_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln_fu_268_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln46_1_fu_303_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln46_2_fu_300_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln46_1_fu_303_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln47_fu_308_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_fu_308_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln46_3_fu_316_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln46_5_fu_313_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln46_3_fu_316_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln47_2_fu_321_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_2_fu_321_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_366_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_374_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_382_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_390_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_366_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_366_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_374_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_374_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_382_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_382_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_390_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_390_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component chan_est_top_mul_16s_15s_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component chan_est_top_mac_muladd_16s_15s_30s_30_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component chan_est_top_mac_mulsub_16s_15s_30s_30_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component chan_est_top_chan_est_top_Pipeline_pilot_scan_DMRS_RE_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component chan_est_top_chan_est_top_Pipeline_pilot_scan_DMRS_IM_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component chan_est_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    DMRS_RE_U : component chan_est_top_chan_est_top_Pipeline_pilot_scan_DMRS_RE_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 172,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => DMRS_RE_address0,
        ce0 => DMRS_RE_ce0_local,
        q0 => DMRS_RE_q0);

    DMRS_IM_U : component chan_est_top_chan_est_top_Pipeline_pilot_scan_DMRS_IM_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 172,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => DMRS_IM_address0,
        ce0 => DMRS_IM_ce0_local,
        q0 => DMRS_IM_q0);

    mul_16s_15s_30_1_1_U13 : component chan_est_top_mul_16s_15s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln46_1_fu_303_p0,
        din1 => mul_ln46_1_fu_303_p1,
        dout => mul_ln46_1_fu_303_p2);

    mul_16s_15s_30_1_1_U14 : component chan_est_top_mul_16s_15s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln47_fu_308_p0,
        din1 => mul_ln47_fu_308_p1,
        dout => mul_ln47_fu_308_p2);

    mul_16s_15s_30_1_1_U15 : component chan_est_top_mul_16s_15s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln46_3_fu_316_p0,
        din1 => mul_ln46_3_fu_316_p1,
        dout => mul_ln46_3_fu_316_p2);

    mul_16s_15s_30_1_1_U16 : component chan_est_top_mul_16s_15s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln47_2_fu_321_p0,
        din1 => mul_ln47_2_fu_321_p1,
        dout => mul_ln47_2_fu_321_p2);

    mac_muladd_16s_15s_30s_30_4_1_U17 : component chan_est_top_mac_muladd_16s_15s_30s_30_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_366_p0,
        din1 => grp_fu_366_p1,
        din2 => mul_ln46_1_reg_492,
        ce => ap_const_logic_1,
        dout => grp_fu_366_p3);

    mac_mulsub_16s_15s_30s_30_4_1_U18 : component chan_est_top_mac_mulsub_16s_15s_30s_30_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_374_p0,
        din1 => grp_fu_374_p1,
        din2 => mul_ln47_reg_497,
        ce => ap_const_logic_1,
        dout => grp_fu_374_p3);

    mac_muladd_16s_15s_30s_30_4_1_U19 : component chan_est_top_mac_muladd_16s_15s_30s_30_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_382_p0,
        din1 => grp_fu_382_p1,
        din2 => mul_ln46_3_reg_502,
        ce => ap_const_logic_1,
        dout => grp_fu_382_p3);

    mac_mulsub_16s_15s_30s_30_4_1_U20 : component chan_est_top_mac_mulsub_16s_15s_30s_30_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_390_p0,
        din1 => grp_fu_390_p1,
        din2 => mul_ln47_2_reg_507,
        ce => ap_const_logic_1,
        dout => grp_fu_390_p3);

    flow_control_loop_pipe_sequential_init_U : component chan_est_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    m_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln246_fu_208_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    m_fu_66 <= add_ln246_fu_214_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    m_fu_66 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                m_1_reg_405 <= ap_sig_allocacmp_m_1;
                    zext_ln246_reg_416(7 downto 0) <= zext_ln246_fu_225_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                mul_ln46_1_reg_492 <= mul_ln46_1_fu_303_p2;
                mul_ln46_3_reg_502 <= mul_ln46_3_fu_316_p2;
                mul_ln47_2_reg_507 <= mul_ln47_2_fu_321_p2;
                mul_ln47_reg_497 <= mul_ln47_fu_308_p2;
                sext_ln46_1_reg_465 <= sext_ln46_1_fu_288_p1;
                sext_ln46_3_reg_473 <= sext_ln46_3_fu_292_p1;
                y_im_1_reg_481 <= fft_im_1_q0;
                y_im_reg_454 <= fft_im_q0;
                    zext_ln246_reg_416_pp0_iter2_reg(7 downto 0) <= zext_ln246_reg_416(7 downto 0);
                    zext_ln246_reg_416_pp0_iter3_reg(7 downto 0) <= zext_ln246_reg_416_pp0_iter2_reg(7 downto 0);
                    zext_ln246_reg_416_pp0_iter4_reg(7 downto 0) <= zext_ln246_reg_416_pp0_iter3_reg(7 downto 0);
            end if;
        end if;
    end process;
    zext_ln246_reg_416(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln246_reg_416_pp0_iter2_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln246_reg_416_pp0_iter3_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln246_reg_416_pp0_iter4_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    DMRS_IM_address0 <= zext_ln246_fu_225_p1(8 - 1 downto 0);

    DMRS_IM_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            DMRS_IM_ce0_local <= ap_const_logic_1;
        else 
            DMRS_IM_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    DMRS_RE_address0 <= zext_ln246_fu_225_p1(8 - 1 downto 0);

    DMRS_RE_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            DMRS_RE_ce0_local <= ap_const_logic_1;
        else 
            DMRS_RE_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln246_fu_214_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_m_1) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln246_fu_208_p2)
    begin
        if (((icmp_ln246_fu_208_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_m_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, m_fu_66, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_m_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_m_1 <= m_fu_66;
        end if; 
    end process;

    fft_im_1_address0 <= zext_ln249_fu_276_p1(10 - 1 downto 0);
    fft_im_1_ce0 <= fft_im_1_ce0_local;

    fft_im_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fft_im_1_ce0_local <= ap_const_logic_1;
        else 
            fft_im_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fft_im_address0 <= zext_ln249_fu_276_p1(10 - 1 downto 0);
    fft_im_ce0 <= fft_im_ce0_local;

    fft_im_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fft_im_ce0_local <= ap_const_logic_1;
        else 
            fft_im_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fft_re_1_address0 <= zext_ln249_fu_276_p1(10 - 1 downto 0);
    fft_re_1_ce0 <= fft_re_1_ce0_local;

    fft_re_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fft_re_1_ce0_local <= ap_const_logic_1;
        else 
            fft_re_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fft_re_address0 <= zext_ln249_fu_276_p1(10 - 1 downto 0);
    fft_re_ce0 <= fft_re_ce0_local;

    fft_re_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fft_re_ce0_local <= ap_const_logic_1;
        else 
            fft_re_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_366_p0 <= sext_ln46_fu_284_p1(16 - 1 downto 0);
    grp_fu_366_p1 <= sext_ln46_1_fu_288_p1(15 - 1 downto 0);
    grp_fu_374_p0 <= sext_ln46_fu_284_p1(16 - 1 downto 0);
    grp_fu_374_p1 <= sext_ln46_3_fu_292_p1(15 - 1 downto 0);
    grp_fu_382_p0 <= sext_ln46_4_fu_296_p1(16 - 1 downto 0);
    grp_fu_382_p1 <= sext_ln46_1_fu_288_p1(15 - 1 downto 0);
    grp_fu_390_p0 <= sext_ln46_4_fu_296_p1(16 - 1 downto 0);
    grp_fu_390_p1 <= sext_ln46_3_fu_292_p1(15 - 1 downto 0);
    icmp_ln246_fu_208_p2 <= "1" when (ap_sig_allocacmp_m_1 = ap_const_lv8_AC) else "0";
    mul_ln46_1_fu_303_p0 <= sext_ln46_2_fu_300_p1(16 - 1 downto 0);
    mul_ln46_1_fu_303_p1 <= sext_ln46_3_reg_473(15 - 1 downto 0);
    mul_ln46_3_fu_316_p0 <= sext_ln46_5_fu_313_p1(16 - 1 downto 0);
    mul_ln46_3_fu_316_p1 <= sext_ln46_3_reg_473(15 - 1 downto 0);
    mul_ln47_2_fu_321_p0 <= sext_ln46_5_fu_313_p1(16 - 1 downto 0);
    mul_ln47_2_fu_321_p1 <= sext_ln46_1_reg_465(15 - 1 downto 0);
    mul_ln47_fu_308_p0 <= sext_ln46_2_fu_300_p1(16 - 1 downto 0);
    mul_ln47_fu_308_p1 <= sext_ln46_1_reg_465(15 - 1 downto 0);
    or_ln_fu_268_p3 <= (tmp_4_fu_258_p4 & ap_const_lv1_1);
    p_shl_fu_233_p3 <= (trunc_ln248_fu_230_p1 & ap_const_lv3_0);
    pilot_h_im_1_address0 <= zext_ln246_reg_416_pp0_iter4_reg(8 - 1 downto 0);
    pilot_h_im_1_ce0 <= pilot_h_im_1_ce0_local;

    pilot_h_im_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pilot_h_im_1_ce0_local <= ap_const_logic_1;
        else 
            pilot_h_im_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pilot_h_im_1_d0 <= grp_fu_390_p3(29 downto 14);
    pilot_h_im_1_we0 <= pilot_h_im_1_we0_local;

    pilot_h_im_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pilot_h_im_1_we0_local <= ap_const_logic_1;
        else 
            pilot_h_im_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pilot_h_im_address0 <= zext_ln246_reg_416_pp0_iter4_reg(8 - 1 downto 0);
    pilot_h_im_ce0 <= pilot_h_im_ce0_local;

    pilot_h_im_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pilot_h_im_ce0_local <= ap_const_logic_1;
        else 
            pilot_h_im_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pilot_h_im_d0 <= grp_fu_374_p3(29 downto 14);
    pilot_h_im_we0 <= pilot_h_im_we0_local;

    pilot_h_im_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pilot_h_im_we0_local <= ap_const_logic_1;
        else 
            pilot_h_im_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pilot_h_re_1_address0 <= zext_ln246_reg_416_pp0_iter4_reg(8 - 1 downto 0);
    pilot_h_re_1_ce0 <= pilot_h_re_1_ce0_local;

    pilot_h_re_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pilot_h_re_1_ce0_local <= ap_const_logic_1;
        else 
            pilot_h_re_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pilot_h_re_1_d0 <= grp_fu_382_p3(29 downto 14);
    pilot_h_re_1_we0 <= pilot_h_re_1_we0_local;

    pilot_h_re_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pilot_h_re_1_we0_local <= ap_const_logic_1;
        else 
            pilot_h_re_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pilot_h_re_address0 <= zext_ln246_reg_416_pp0_iter4_reg(8 - 1 downto 0);
    pilot_h_re_ce0 <= pilot_h_re_ce0_local;

    pilot_h_re_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pilot_h_re_ce0_local <= ap_const_logic_1;
        else 
            pilot_h_re_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pilot_h_re_d0 <= grp_fu_366_p3(29 downto 14);
    pilot_h_re_we0 <= pilot_h_re_we0_local;

    pilot_h_re_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pilot_h_re_we0_local <= ap_const_logic_1;
        else 
            pilot_h_re_we0_local <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln46_1_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(DMRS_RE_q0),30));

        sext_ln46_2_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(y_im_reg_454),30));

        sext_ln46_3_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(DMRS_IM_q0),30));

        sext_ln46_4_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(fft_re_1_q0),30));

        sext_ln46_5_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(y_im_1_reg_481),30));

        sext_ln46_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(fft_re_q0),30));

    sub_ln248_fu_252_p2 <= std_logic_vector(unsigned(p_shl_fu_233_p3) - unsigned(zext_ln248_fu_248_p1));
    tmp_4_fu_258_p4 <= sub_ln248_fu_252_p2(9 downto 1);
    tmp_fu_241_p3 <= (m_1_reg_405 & ap_const_lv1_0);
    trunc_ln248_fu_230_p1 <= m_1_reg_405(7 - 1 downto 0);
    zext_ln246_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_1_reg_405),64));
    zext_ln248_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_241_p3),10));
    zext_ln249_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_268_p3),64));
end behav;
