-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity beamformer_top_beamformer_top_Pipeline_subcarrier_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_0_TVALID : IN STD_LOGIC;
    in_stream_1_TVALID : IN STD_LOGIC;
    out_stream_0_TREADY : IN STD_LOGIC;
    out_stream_1_TREADY : IN STD_LOGIC;
    in_stream_0_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_0_TREADY : OUT STD_LOGIC;
    in_stream_0_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_0_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_1_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_1_TREADY : OUT STD_LOGIC;
    in_stream_1_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_1_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    weights_re_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weights_re_ce0 : OUT STD_LOGIC;
    weights_re_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    weights_im_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weights_im_ce0 : OUT STD_LOGIC;
    weights_im_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    weights_re_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weights_re_1_ce0 : OUT STD_LOGIC;
    weights_re_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    weights_im_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weights_im_1_ce0 : OUT STD_LOGIC;
    weights_im_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    out_stream_0_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_0_TVALID : OUT STD_LOGIC;
    out_stream_0_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_0_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_0_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    weights_re_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weights_re_2_ce0 : OUT STD_LOGIC;
    weights_re_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    weights_im_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weights_im_2_ce0 : OUT STD_LOGIC;
    weights_im_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    weights_re_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weights_re_3_ce0 : OUT STD_LOGIC;
    weights_re_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    weights_im_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weights_im_3_ce0 : OUT STD_LOGIC;
    weights_im_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    out_stream_1_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_1_TVALID : OUT STD_LOGIC;
    out_stream_1_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_1_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_1_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of beamformer_top_beamformer_top_Pipeline_subcarrier_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln137_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_0_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal in_stream_1_TDATA_blk_n : STD_LOGIC;
    signal out_stream_0_TDATA_blk_n : STD_LOGIC;
    signal out_stream_1_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal x_re_fu_326_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_re_reg_1348 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_re_reg_1348_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_im_reg_1353 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_im_reg_1353_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal s_last_reg_1358 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_last_reg_1358_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal s_last_reg_1358_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal s_last_reg_1358_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_re_1_fu_348_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_re_1_reg_1364 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_re_1_reg_1364_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_im_1_reg_1369 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_im_1_reg_1369_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal w_re_reg_1414 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_im_reg_1419 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_re_1_reg_1424 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_im_1_reg_1429 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_re_2_reg_1434 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_im_2_reg_1439 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_re_3_reg_1444 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_im_3_reg_1449 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln74_fu_373_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_reg_1454 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_cast_reg_1459 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln74_fu_389_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln74_reg_1466 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln74_1_fu_399_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_1_reg_1471 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_cast_reg_1476 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln74_1_fu_415_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln74_1_reg_1483 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln75_fu_419_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_reg_1488 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_cast_reg_1493 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln75_fu_435_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln75_reg_1500 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln75_1_fu_439_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_1_reg_1505 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_cast_reg_1510 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln75_1_fu_455_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln75_1_reg_1517 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln74_2_fu_465_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_2_reg_1522 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_cast_reg_1527 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln74_2_fu_481_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln74_2_reg_1534 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln74_3_fu_491_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_3_reg_1539 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_cast_reg_1544 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln74_3_fu_507_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln74_3_reg_1551 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln75_2_fu_511_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_2_reg_1556 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_cast_reg_1561 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln75_2_fu_527_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln75_2_reg_1568 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln75_3_fu_531_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_3_reg_1573 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_cast_reg_1578 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln75_3_fu_547_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln75_3_reg_1585 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln74_4_fu_554_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_4_reg_1590 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_cast_reg_1595 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln74_4_fu_570_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln74_4_reg_1602 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln74_5_fu_577_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_5_reg_1607 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_28_cast_reg_1612 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln74_5_fu_593_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln74_5_reg_1619 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln75_4_fu_597_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_4_reg_1624 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_31_cast_reg_1629 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln75_4_fu_613_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln75_4_reg_1636 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln75_5_fu_617_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_5_reg_1641 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_cast_reg_1646 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln75_5_fu_633_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln75_5_reg_1653 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln74_6_fu_640_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_6_reg_1658 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_37_cast_reg_1663 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln74_6_fu_656_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln74_6_reg_1670 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln74_7_fu_663_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_7_reg_1675 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_40_cast_reg_1680 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln74_7_fu_679_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln74_7_reg_1687 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln75_6_fu_683_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_6_reg_1692 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_43_cast_reg_1697 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln75_6_fu_699_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln75_6_reg_1704 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln75_7_fu_703_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_7_reg_1709 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_46_cast_reg_1714 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln75_7_fu_719_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln75_7_reg_1721 : STD_LOGIC_VECTOR (13 downto 0);
    signal ref_tmp_i_i321_i_0_fu_747_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i321_i_0_reg_1726 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i214_i_0_fu_778_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i214_i_0_reg_1731 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln74_5_fu_909_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln74_5_reg_1736 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i84_i_0_1601_fu_939_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i84_i_0_1601_reg_1741 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i_i_0_1622_fu_970_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i_i_0_1622_reg_1746 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln75_fu_977_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln75_reg_1751 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i321_i_0_1_fu_1007_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i321_i_0_1_reg_1756 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i214_i_0_1_fu_1038_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i214_i_0_1_reg_1761 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln74_12_fu_1169_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln74_12_reg_1766 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i84_i_0_1_1_fu_1199_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i84_i_0_1_1_reg_1771 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i_i_0_1_1_fu_1230_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i_i_0_1_1_reg_1776 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln75_2_fu_1237_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln75_2_reg_1781 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln137_fu_310_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal k_fu_122 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln137_fu_304_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal weights_re_ce0_local : STD_LOGIC;
    signal weights_im_ce0_local : STD_LOGIC;
    signal weights_re_1_ce0_local : STD_LOGIC;
    signal weights_im_1_ce0_local : STD_LOGIC;
    signal weights_re_2_ce0_local : STD_LOGIC;
    signal weights_im_2_ce0_local : STD_LOGIC;
    signal weights_re_3_ce0_local : STD_LOGIC;
    signal weights_im_3_ce0_local : STD_LOGIC;
    signal mul_ln74_fu_373_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_1_fu_370_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_fu_373_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_fu_367_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_1_fu_399_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_3_fu_396_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_1_fu_399_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_2_fu_393_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_fu_419_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_fu_419_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_1_fu_439_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_1_fu_439_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln74_2_fu_465_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_5_fu_462_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_2_fu_465_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_4_fu_459_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_3_fu_491_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_7_fu_488_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_3_fu_491_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_6_fu_485_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln75_2_fu_511_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_2_fu_511_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_3_fu_531_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_3_fu_531_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln74_4_fu_554_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_8_fu_551_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_4_fu_554_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln74_5_fu_577_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_9_fu_574_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_5_fu_577_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_4_fu_597_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_4_fu_597_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_5_fu_617_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_5_fu_617_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln74_6_fu_640_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_10_fu_637_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_6_fu_640_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln74_7_fu_663_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_11_fu_660_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_7_fu_663_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_6_fu_683_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_6_fu_683_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_7_fu_703_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln75_7_fu_703_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln74_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_fu_735_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_723_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_fu_740_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln74_1_fu_761_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_1_fu_766_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_754_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_1_fu_771_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln75_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_fu_797_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_4_fu_785_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_fu_802_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln75_1_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_1_fu_828_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_5_fu_816_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_1_fu_833_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln74_2_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_2_fu_859_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_6_fu_847_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_2_fu_864_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln74_3_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_3_fu_890_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_7_fu_878_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_3_fu_895_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i321_i_0_1558_fu_871_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i214_i_0_1579_fu_902_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln75_2_fu_922_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_2_fu_927_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_8_fu_915_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_2_fu_932_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln75_3_fu_953_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_3_fu_958_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_9_fu_946_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_3_fu_963_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i84_i_0_fu_809_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i_i_0_fu_840_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln74_4_fu_990_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_7_fu_995_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_10_fu_983_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_4_fu_1000_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln74_5_fu_1021_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_8_fu_1026_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_11_fu_1014_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_5_fu_1031_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln75_4_fu_1052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_5_fu_1057_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_12_fu_1045_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_4_fu_1062_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln75_5_fu_1083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_6_fu_1088_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_13_fu_1076_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_5_fu_1093_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln74_6_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_9_fu_1119_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_14_fu_1107_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_6_fu_1124_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln74_7_fu_1145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_10_fu_1150_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_15_fu_1138_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_7_fu_1155_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i321_i_0_1_1_fu_1131_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i214_i_0_1_1_fu_1162_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln75_6_fu_1182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_7_fu_1187_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_16_fu_1175_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_6_fu_1192_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln75_7_fu_1213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_8_fu_1218_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_17_fu_1206_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_7_fu_1223_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i84_i_0_1_fu_1069_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ref_tmp_i_i_i_0_1_fu_1100_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln74_4_fu_1243_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal acc_im_4_fu_1252_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal acc_re_fu_1247_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal acc_im_fu_1256_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal out_im_fu_1271_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_re_fu_1261_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_11_fu_1290_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal acc_im_5_fu_1299_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal acc_re_1_fu_1294_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal acc_im_3_fu_1303_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal out_im_1_fu_1318_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_re_1_fu_1308_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component beamformer_top_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component beamformer_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_16s_16s_32_1_1_U13 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln74_fu_373_p0,
        din1 => mul_ln74_fu_373_p1,
        dout => mul_ln74_fu_373_p2);

    mul_16s_16s_32_1_1_U14 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln74_1_fu_399_p0,
        din1 => mul_ln74_1_fu_399_p1,
        dout => mul_ln74_1_fu_399_p2);

    mul_16s_16s_32_1_1_U15 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln75_fu_419_p0,
        din1 => mul_ln75_fu_419_p1,
        dout => mul_ln75_fu_419_p2);

    mul_16s_16s_32_1_1_U16 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln75_1_fu_439_p0,
        din1 => mul_ln75_1_fu_439_p1,
        dout => mul_ln75_1_fu_439_p2);

    mul_16s_16s_32_1_1_U17 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln74_2_fu_465_p0,
        din1 => mul_ln74_2_fu_465_p1,
        dout => mul_ln74_2_fu_465_p2);

    mul_16s_16s_32_1_1_U18 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln74_3_fu_491_p0,
        din1 => mul_ln74_3_fu_491_p1,
        dout => mul_ln74_3_fu_491_p2);

    mul_16s_16s_32_1_1_U19 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln75_2_fu_511_p0,
        din1 => mul_ln75_2_fu_511_p1,
        dout => mul_ln75_2_fu_511_p2);

    mul_16s_16s_32_1_1_U20 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln75_3_fu_531_p0,
        din1 => mul_ln75_3_fu_531_p1,
        dout => mul_ln75_3_fu_531_p2);

    mul_16s_16s_32_1_1_U21 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln74_4_fu_554_p0,
        din1 => mul_ln74_4_fu_554_p1,
        dout => mul_ln74_4_fu_554_p2);

    mul_16s_16s_32_1_1_U22 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln74_5_fu_577_p0,
        din1 => mul_ln74_5_fu_577_p1,
        dout => mul_ln74_5_fu_577_p2);

    mul_16s_16s_32_1_1_U23 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln75_4_fu_597_p0,
        din1 => mul_ln75_4_fu_597_p1,
        dout => mul_ln75_4_fu_597_p2);

    mul_16s_16s_32_1_1_U24 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln75_5_fu_617_p0,
        din1 => mul_ln75_5_fu_617_p1,
        dout => mul_ln75_5_fu_617_p2);

    mul_16s_16s_32_1_1_U25 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln74_6_fu_640_p0,
        din1 => mul_ln74_6_fu_640_p1,
        dout => mul_ln74_6_fu_640_p2);

    mul_16s_16s_32_1_1_U26 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln74_7_fu_663_p0,
        din1 => mul_ln74_7_fu_663_p1,
        dout => mul_ln74_7_fu_663_p2);

    mul_16s_16s_32_1_1_U27 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln75_6_fu_683_p0,
        din1 => mul_ln75_6_fu_683_p1,
        dout => mul_ln75_6_fu_683_p2);

    mul_16s_16s_32_1_1_U28 : component beamformer_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln75_7_fu_703_p0,
        din1 => mul_ln75_7_fu_703_p1,
        dout => mul_ln75_7_fu_703_p2);

    flow_control_loop_pipe_sequential_init_U : component beamformer_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    k_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln137_fu_298_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    k_fu_122 <= add_ln137_fu_304_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_122 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln74_12_reg_1766 <= add_ln74_12_fu_1169_p2;
                add_ln74_5_reg_1736 <= add_ln74_5_fu_909_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                mul_ln74_1_reg_1471 <= mul_ln74_1_fu_399_p2;
                mul_ln74_2_reg_1522 <= mul_ln74_2_fu_465_p2;
                mul_ln74_3_reg_1539 <= mul_ln74_3_fu_491_p2;
                mul_ln74_4_reg_1590 <= mul_ln74_4_fu_554_p2;
                mul_ln74_5_reg_1607 <= mul_ln74_5_fu_577_p2;
                mul_ln74_6_reg_1658 <= mul_ln74_6_fu_640_p2;
                mul_ln74_7_reg_1675 <= mul_ln74_7_fu_663_p2;
                mul_ln74_reg_1454 <= mul_ln74_fu_373_p2;
                mul_ln75_1_reg_1505 <= mul_ln75_1_fu_439_p2;
                mul_ln75_2_reg_1556 <= mul_ln75_2_fu_511_p2;
                mul_ln75_3_reg_1573 <= mul_ln75_3_fu_531_p2;
                mul_ln75_4_reg_1624 <= mul_ln75_4_fu_597_p2;
                mul_ln75_5_reg_1641 <= mul_ln75_5_fu_617_p2;
                mul_ln75_6_reg_1692 <= mul_ln75_6_fu_683_p2;
                mul_ln75_7_reg_1709 <= mul_ln75_7_fu_703_p2;
                mul_ln75_reg_1488 <= mul_ln75_fu_419_p2;
                ref_tmp_i_i214_i_0_1_reg_1761 <= ref_tmp_i_i214_i_0_1_fu_1038_p3;
                ref_tmp_i_i214_i_0_reg_1731 <= ref_tmp_i_i214_i_0_fu_778_p3;
                ref_tmp_i_i321_i_0_1_reg_1756 <= ref_tmp_i_i321_i_0_1_fu_1007_p3;
                ref_tmp_i_i321_i_0_reg_1726 <= ref_tmp_i_i321_i_0_fu_747_p3;
                ref_tmp_i_i84_i_0_1601_reg_1741 <= ref_tmp_i_i84_i_0_1601_fu_939_p3;
                ref_tmp_i_i84_i_0_1_1_reg_1771 <= ref_tmp_i_i84_i_0_1_1_fu_1199_p3;
                ref_tmp_i_i_i_0_1622_reg_1746 <= ref_tmp_i_i_i_0_1622_fu_970_p3;
                ref_tmp_i_i_i_0_1_1_reg_1776 <= ref_tmp_i_i_i_0_1_1_fu_1230_p3;
                s_last_reg_1358_pp0_iter2_reg <= s_last_reg_1358_pp0_iter1_reg;
                s_last_reg_1358_pp0_iter3_reg <= s_last_reg_1358_pp0_iter2_reg;
                sub_ln75_2_reg_1781 <= sub_ln75_2_fu_1237_p2;
                sub_ln75_reg_1751 <= sub_ln75_fu_977_p2;
                tmp_10_cast_reg_1510 <= mul_ln75_1_fu_439_p2(30 downto 14);
                tmp_13_cast_reg_1527 <= mul_ln74_2_fu_465_p2(30 downto 14);
                tmp_16_cast_reg_1544 <= mul_ln74_3_fu_491_p2(30 downto 14);
                tmp_19_cast_reg_1561 <= mul_ln75_2_fu_511_p2(30 downto 14);
                tmp_22_cast_reg_1578 <= mul_ln75_3_fu_531_p2(30 downto 14);
                tmp_25_cast_reg_1595 <= mul_ln74_4_fu_554_p2(30 downto 14);
                tmp_28_cast_reg_1612 <= mul_ln74_5_fu_577_p2(30 downto 14);
                tmp_31_cast_reg_1629 <= mul_ln75_4_fu_597_p2(30 downto 14);
                tmp_34_cast_reg_1646 <= mul_ln75_5_fu_617_p2(30 downto 14);
                tmp_37_cast_reg_1663 <= mul_ln74_6_fu_640_p2(30 downto 14);
                tmp_3_cast_reg_1493 <= mul_ln75_fu_419_p2(30 downto 14);
                tmp_40_cast_reg_1680 <= mul_ln74_7_fu_663_p2(30 downto 14);
                tmp_43_cast_reg_1697 <= mul_ln75_6_fu_683_p2(30 downto 14);
                tmp_46_cast_reg_1714 <= mul_ln75_7_fu_703_p2(30 downto 14);
                tmp_6_cast_reg_1459 <= mul_ln74_fu_373_p2(30 downto 14);
                tmp_9_cast_reg_1476 <= mul_ln74_1_fu_399_p2(30 downto 14);
                trunc_ln74_1_reg_1483 <= trunc_ln74_1_fu_415_p1;
                trunc_ln74_2_reg_1534 <= trunc_ln74_2_fu_481_p1;
                trunc_ln74_3_reg_1551 <= trunc_ln74_3_fu_507_p1;
                trunc_ln74_4_reg_1602 <= trunc_ln74_4_fu_570_p1;
                trunc_ln74_5_reg_1619 <= trunc_ln74_5_fu_593_p1;
                trunc_ln74_6_reg_1670 <= trunc_ln74_6_fu_656_p1;
                trunc_ln74_7_reg_1687 <= trunc_ln74_7_fu_679_p1;
                trunc_ln74_reg_1466 <= trunc_ln74_fu_389_p1;
                trunc_ln75_1_reg_1517 <= trunc_ln75_1_fu_455_p1;
                trunc_ln75_2_reg_1568 <= trunc_ln75_2_fu_527_p1;
                trunc_ln75_3_reg_1585 <= trunc_ln75_3_fu_547_p1;
                trunc_ln75_4_reg_1636 <= trunc_ln75_4_fu_613_p1;
                trunc_ln75_5_reg_1653 <= trunc_ln75_5_fu_633_p1;
                trunc_ln75_6_reg_1704 <= trunc_ln75_6_fu_699_p1;
                trunc_ln75_7_reg_1721 <= trunc_ln75_7_fu_719_p1;
                trunc_ln75_reg_1500 <= trunc_ln75_fu_435_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                s_last_reg_1358 <= in_stream_1_TLAST;
                s_last_reg_1358_pp0_iter1_reg <= s_last_reg_1358;
                w_im_1_reg_1429 <= weights_im_1_q0;
                w_im_2_reg_1439 <= weights_im_2_q0;
                w_im_3_reg_1449 <= weights_im_3_q0;
                w_im_reg_1419 <= weights_im_q0;
                w_re_1_reg_1424 <= weights_re_1_q0;
                w_re_2_reg_1434 <= weights_re_2_q0;
                w_re_3_reg_1444 <= weights_re_3_q0;
                w_re_reg_1414 <= weights_re_q0;
                x_im_1_reg_1369 <= in_stream_1_TDATA(31 downto 16);
                x_im_1_reg_1369_pp0_iter1_reg <= x_im_1_reg_1369;
                x_im_reg_1353 <= in_stream_0_TDATA(31 downto 16);
                x_im_reg_1353_pp0_iter1_reg <= x_im_reg_1353;
                x_re_1_reg_1364 <= x_re_1_fu_348_p1;
                x_re_1_reg_1364_pp0_iter1_reg <= x_re_1_reg_1364;
                x_re_reg_1348 <= x_re_fu_326_p1;
                x_re_reg_1348_pp0_iter1_reg <= x_re_reg_1348;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_im_3_fu_1303_p2 <= std_logic_vector(unsigned(acc_im_5_fu_1299_p2) - unsigned(ref_tmp_i_i_i_0_1_1_reg_1776));
    acc_im_4_fu_1252_p2 <= std_logic_vector(unsigned(sub_ln75_reg_1751) + unsigned(ref_tmp_i_i84_i_0_1601_reg_1741));
    acc_im_5_fu_1299_p2 <= std_logic_vector(unsigned(sub_ln75_2_reg_1781) + unsigned(ref_tmp_i_i84_i_0_1_1_reg_1771));
    acc_im_fu_1256_p2 <= std_logic_vector(unsigned(acc_im_4_fu_1252_p2) - unsigned(ref_tmp_i_i_i_0_1622_reg_1746));
    acc_re_1_fu_1294_p2 <= std_logic_vector(unsigned(add_ln74_12_reg_1766) + unsigned(add_ln74_11_fu_1290_p2));
    acc_re_fu_1247_p2 <= std_logic_vector(unsigned(add_ln74_5_reg_1736) + unsigned(add_ln74_4_fu_1243_p2));
    add_ln137_fu_304_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv11_1));
    add_ln74_10_fu_1150_p2 <= std_logic_vector(unsigned(tmp_40_cast_reg_1680) + unsigned(ap_const_lv17_1));
    add_ln74_11_fu_1290_p2 <= std_logic_vector(unsigned(ref_tmp_i_i214_i_0_1_reg_1761) + unsigned(ref_tmp_i_i321_i_0_1_reg_1756));
    add_ln74_12_fu_1169_p2 <= std_logic_vector(unsigned(ref_tmp_i_i321_i_0_1_1_fu_1131_p3) + unsigned(ref_tmp_i_i214_i_0_1_1_fu_1162_p3));
    add_ln74_1_fu_766_p2 <= std_logic_vector(unsigned(tmp_9_cast_reg_1476) + unsigned(ap_const_lv17_1));
    add_ln74_2_fu_859_p2 <= std_logic_vector(unsigned(tmp_13_cast_reg_1527) + unsigned(ap_const_lv17_1));
    add_ln74_3_fu_890_p2 <= std_logic_vector(unsigned(tmp_16_cast_reg_1544) + unsigned(ap_const_lv17_1));
    add_ln74_4_fu_1243_p2 <= std_logic_vector(unsigned(ref_tmp_i_i214_i_0_reg_1731) + unsigned(ref_tmp_i_i321_i_0_reg_1726));
    add_ln74_5_fu_909_p2 <= std_logic_vector(unsigned(ref_tmp_i_i321_i_0_1558_fu_871_p3) + unsigned(ref_tmp_i_i214_i_0_1579_fu_902_p3));
    add_ln74_7_fu_995_p2 <= std_logic_vector(unsigned(tmp_25_cast_reg_1595) + unsigned(ap_const_lv17_1));
    add_ln74_8_fu_1026_p2 <= std_logic_vector(unsigned(tmp_28_cast_reg_1612) + unsigned(ap_const_lv17_1));
    add_ln74_9_fu_1119_p2 <= std_logic_vector(unsigned(tmp_37_cast_reg_1663) + unsigned(ap_const_lv17_1));
    add_ln74_fu_735_p2 <= std_logic_vector(unsigned(tmp_6_cast_reg_1459) + unsigned(ap_const_lv17_1));
    add_ln75_1_fu_828_p2 <= std_logic_vector(unsigned(tmp_10_cast_reg_1510) + unsigned(ap_const_lv17_1));
    add_ln75_2_fu_927_p2 <= std_logic_vector(unsigned(tmp_19_cast_reg_1561) + unsigned(ap_const_lv17_1));
    add_ln75_3_fu_958_p2 <= std_logic_vector(unsigned(tmp_22_cast_reg_1578) + unsigned(ap_const_lv17_1));
    add_ln75_5_fu_1057_p2 <= std_logic_vector(unsigned(tmp_31_cast_reg_1629) + unsigned(ap_const_lv17_1));
    add_ln75_6_fu_1088_p2 <= std_logic_vector(unsigned(tmp_34_cast_reg_1646) + unsigned(ap_const_lv17_1));
    add_ln75_7_fu_1187_p2 <= std_logic_vector(unsigned(tmp_43_cast_reg_1697) + unsigned(ap_const_lv17_1));
    add_ln75_8_fu_1218_p2 <= std_logic_vector(unsigned(tmp_46_cast_reg_1714) + unsigned(ap_const_lv17_1));
    add_ln75_fu_797_p2 <= std_logic_vector(unsigned(tmp_3_cast_reg_1493) + unsigned(ap_const_lv17_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state1_pp0_stage0_iter0, ap_block_state5_pp0_stage0_iter4, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state1_pp0_stage0_iter0, ap_block_state5_pp0_stage0_iter4, ap_block_state5_io, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state1_pp0_stage0_iter0, ap_block_state5_pp0_stage0_iter4, ap_block_state5_io, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_0_TVALID, icmp_ln137_fu_298_p2, in_stream_1_TVALID)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (((in_stream_1_TVALID = ap_const_logic_0) and (icmp_ln137_fu_298_p2 = ap_const_lv1_0)) or ((icmp_ln137_fu_298_p2 = ap_const_lv1_0) and (in_stream_0_TVALID = ap_const_logic_0)));
    end process;


    ap_block_state5_io_assign_proc : process(out_stream_0_TREADY, out_stream_1_TREADY)
    begin
                ap_block_state5_io <= ((out_stream_1_TREADY = ap_const_logic_0) or (out_stream_0_TREADY = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(out_stream_0_TREADY, out_stream_1_TREADY)
    begin
                ap_block_state5_pp0_stage0_iter4 <= ((out_stream_1_TREADY = ap_const_logic_0) or (out_stream_0_TREADY = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln137_fu_298_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln137_fu_298_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, k_fu_122, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_122;
        end if; 
    end process;

    icmp_ln137_fu_298_p2 <= "1" when (ap_sig_allocacmp_k_1 = ap_const_lv11_400) else "0";
    icmp_ln74_1_fu_761_p2 <= "0" when (trunc_ln74_1_reg_1483 = ap_const_lv14_0) else "1";
    icmp_ln74_2_fu_854_p2 <= "0" when (trunc_ln74_2_reg_1534 = ap_const_lv14_0) else "1";
    icmp_ln74_3_fu_885_p2 <= "0" when (trunc_ln74_3_reg_1551 = ap_const_lv14_0) else "1";
    icmp_ln74_4_fu_990_p2 <= "0" when (trunc_ln74_4_reg_1602 = ap_const_lv14_0) else "1";
    icmp_ln74_5_fu_1021_p2 <= "0" when (trunc_ln74_5_reg_1619 = ap_const_lv14_0) else "1";
    icmp_ln74_6_fu_1114_p2 <= "0" when (trunc_ln74_6_reg_1670 = ap_const_lv14_0) else "1";
    icmp_ln74_7_fu_1145_p2 <= "0" when (trunc_ln74_7_reg_1687 = ap_const_lv14_0) else "1";
    icmp_ln74_fu_730_p2 <= "0" when (trunc_ln74_reg_1466 = ap_const_lv14_0) else "1";
    icmp_ln75_1_fu_823_p2 <= "0" when (trunc_ln75_1_reg_1517 = ap_const_lv14_0) else "1";
    icmp_ln75_2_fu_922_p2 <= "0" when (trunc_ln75_2_reg_1568 = ap_const_lv14_0) else "1";
    icmp_ln75_3_fu_953_p2 <= "0" when (trunc_ln75_3_reg_1585 = ap_const_lv14_0) else "1";
    icmp_ln75_4_fu_1052_p2 <= "0" when (trunc_ln75_4_reg_1636 = ap_const_lv14_0) else "1";
    icmp_ln75_5_fu_1083_p2 <= "0" when (trunc_ln75_5_reg_1653 = ap_const_lv14_0) else "1";
    icmp_ln75_6_fu_1182_p2 <= "0" when (trunc_ln75_6_reg_1704 = ap_const_lv14_0) else "1";
    icmp_ln75_7_fu_1213_p2 <= "0" when (trunc_ln75_7_reg_1721 = ap_const_lv14_0) else "1";
    icmp_ln75_fu_792_p2 <= "0" when (trunc_ln75_reg_1500 = ap_const_lv14_0) else "1";

    in_stream_0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, in_stream_0_TVALID, icmp_ln137_fu_298_p2, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln137_fu_298_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_0_TDATA_blk_n <= in_stream_0_TVALID;
        else 
            in_stream_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_0_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln137_fu_298_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln137_fu_298_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_0_TREADY <= ap_const_logic_1;
        else 
            in_stream_0_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    in_stream_1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln137_fu_298_p2, in_stream_1_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln137_fu_298_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_1_TDATA_blk_n <= in_stream_1_TVALID;
        else 
            in_stream_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_1_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln137_fu_298_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln137_fu_298_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_1_TREADY <= ap_const_logic_1;
        else 
            in_stream_1_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln74_1_fu_399_p0 <= sext_ln74_3_fu_396_p1(16 - 1 downto 0);
    mul_ln74_1_fu_399_p1 <= sext_ln74_2_fu_393_p1(16 - 1 downto 0);
    mul_ln74_2_fu_465_p0 <= sext_ln74_5_fu_462_p1(16 - 1 downto 0);
    mul_ln74_2_fu_465_p1 <= sext_ln74_4_fu_459_p1(16 - 1 downto 0);
    mul_ln74_3_fu_491_p0 <= sext_ln74_7_fu_488_p1(16 - 1 downto 0);
    mul_ln74_3_fu_491_p1 <= sext_ln74_6_fu_485_p1(16 - 1 downto 0);
    mul_ln74_4_fu_554_p0 <= sext_ln74_8_fu_551_p1(16 - 1 downto 0);
    mul_ln74_4_fu_554_p1 <= sext_ln74_fu_367_p1(16 - 1 downto 0);
    mul_ln74_5_fu_577_p0 <= sext_ln74_9_fu_574_p1(16 - 1 downto 0);
    mul_ln74_5_fu_577_p1 <= sext_ln74_2_fu_393_p1(16 - 1 downto 0);
    mul_ln74_6_fu_640_p0 <= sext_ln74_10_fu_637_p1(16 - 1 downto 0);
    mul_ln74_6_fu_640_p1 <= sext_ln74_4_fu_459_p1(16 - 1 downto 0);
    mul_ln74_7_fu_663_p0 <= sext_ln74_11_fu_660_p1(16 - 1 downto 0);
    mul_ln74_7_fu_663_p1 <= sext_ln74_6_fu_485_p1(16 - 1 downto 0);
    mul_ln74_fu_373_p0 <= sext_ln74_1_fu_370_p1(16 - 1 downto 0);
    mul_ln74_fu_373_p1 <= sext_ln74_fu_367_p1(16 - 1 downto 0);
    mul_ln75_1_fu_439_p0 <= sext_ln74_3_fu_396_p1(16 - 1 downto 0);
    mul_ln75_1_fu_439_p1 <= sext_ln74_fu_367_p1(16 - 1 downto 0);
    mul_ln75_2_fu_511_p0 <= sext_ln74_5_fu_462_p1(16 - 1 downto 0);
    mul_ln75_2_fu_511_p1 <= sext_ln74_6_fu_485_p1(16 - 1 downto 0);
    mul_ln75_3_fu_531_p0 <= sext_ln74_7_fu_488_p1(16 - 1 downto 0);
    mul_ln75_3_fu_531_p1 <= sext_ln74_4_fu_459_p1(16 - 1 downto 0);
    mul_ln75_4_fu_597_p0 <= sext_ln74_8_fu_551_p1(16 - 1 downto 0);
    mul_ln75_4_fu_597_p1 <= sext_ln74_2_fu_393_p1(16 - 1 downto 0);
    mul_ln75_5_fu_617_p0 <= sext_ln74_9_fu_574_p1(16 - 1 downto 0);
    mul_ln75_5_fu_617_p1 <= sext_ln74_fu_367_p1(16 - 1 downto 0);
    mul_ln75_6_fu_683_p0 <= sext_ln74_10_fu_637_p1(16 - 1 downto 0);
    mul_ln75_6_fu_683_p1 <= sext_ln74_6_fu_485_p1(16 - 1 downto 0);
    mul_ln75_7_fu_703_p0 <= sext_ln74_11_fu_660_p1(16 - 1 downto 0);
    mul_ln75_7_fu_703_p1 <= sext_ln74_4_fu_459_p1(16 - 1 downto 0);
    mul_ln75_fu_419_p0 <= sext_ln74_1_fu_370_p1(16 - 1 downto 0);
    mul_ln75_fu_419_p1 <= sext_ln74_2_fu_393_p1(16 - 1 downto 0);
    out_im_1_fu_1318_p4 <= acc_im_3_fu_1303_p2(16 downto 1);
    out_im_fu_1271_p4 <= acc_im_fu_1256_p2(16 downto 1);
    out_re_1_fu_1308_p4 <= acc_re_1_fu_1294_p2(16 downto 1);
    out_re_fu_1261_p4 <= acc_re_fu_1247_p2(16 downto 1);
    out_stream_0_TDATA <= (out_im_fu_1271_p4 & out_re_fu_1261_p4);

    out_stream_0_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, out_stream_0_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_0_TDATA_blk_n <= out_stream_0_TREADY;
        else 
            out_stream_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_0_TKEEP <= ap_const_lv4_F;
    out_stream_0_TLAST <= s_last_reg_1358_pp0_iter3_reg;
    out_stream_0_TSTRB <= "XXXX";

    out_stream_0_TVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_0_TVALID <= ap_const_logic_1;
        else 
            out_stream_0_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_1_TDATA <= (out_im_1_fu_1318_p4 & out_re_1_fu_1308_p4);

    out_stream_1_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, out_stream_1_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_1_TDATA_blk_n <= out_stream_1_TREADY;
        else 
            out_stream_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_1_TKEEP <= ap_const_lv4_F;
    out_stream_1_TLAST <= s_last_reg_1358_pp0_iter3_reg;
    out_stream_1_TSTRB <= "XXXX";

    out_stream_1_TVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_1_TVALID <= ap_const_logic_1;
        else 
            out_stream_1_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    ref_tmp_i_i214_i_0_1579_fu_902_p3 <= 
        select_ln74_3_fu_895_p3 when (tmp_7_fu_878_p3(0) = '1') else 
        tmp_16_cast_reg_1544;
    ref_tmp_i_i214_i_0_1_1_fu_1162_p3 <= 
        select_ln74_7_fu_1155_p3 when (tmp_15_fu_1138_p3(0) = '1') else 
        tmp_40_cast_reg_1680;
    ref_tmp_i_i214_i_0_1_fu_1038_p3 <= 
        select_ln74_5_fu_1031_p3 when (tmp_11_fu_1014_p3(0) = '1') else 
        tmp_28_cast_reg_1612;
    ref_tmp_i_i214_i_0_fu_778_p3 <= 
        select_ln74_1_fu_771_p3 when (tmp_3_fu_754_p3(0) = '1') else 
        tmp_9_cast_reg_1476;
    ref_tmp_i_i321_i_0_1558_fu_871_p3 <= 
        select_ln74_2_fu_864_p3 when (tmp_6_fu_847_p3(0) = '1') else 
        tmp_13_cast_reg_1527;
    ref_tmp_i_i321_i_0_1_1_fu_1131_p3 <= 
        select_ln74_6_fu_1124_p3 when (tmp_14_fu_1107_p3(0) = '1') else 
        tmp_37_cast_reg_1663;
    ref_tmp_i_i321_i_0_1_fu_1007_p3 <= 
        select_ln74_4_fu_1000_p3 when (tmp_10_fu_983_p3(0) = '1') else 
        tmp_25_cast_reg_1595;
    ref_tmp_i_i321_i_0_fu_747_p3 <= 
        select_ln74_fu_740_p3 when (tmp_fu_723_p3(0) = '1') else 
        tmp_6_cast_reg_1459;
    ref_tmp_i_i84_i_0_1601_fu_939_p3 <= 
        select_ln75_2_fu_932_p3 when (tmp_8_fu_915_p3(0) = '1') else 
        tmp_19_cast_reg_1561;
    ref_tmp_i_i84_i_0_1_1_fu_1199_p3 <= 
        select_ln75_6_fu_1192_p3 when (tmp_16_fu_1175_p3(0) = '1') else 
        tmp_43_cast_reg_1697;
    ref_tmp_i_i84_i_0_1_fu_1069_p3 <= 
        select_ln75_4_fu_1062_p3 when (tmp_12_fu_1045_p3(0) = '1') else 
        tmp_31_cast_reg_1629;
    ref_tmp_i_i84_i_0_fu_809_p3 <= 
        select_ln75_fu_802_p3 when (tmp_4_fu_785_p3(0) = '1') else 
        tmp_3_cast_reg_1493;
    ref_tmp_i_i_i_0_1622_fu_970_p3 <= 
        select_ln75_3_fu_963_p3 when (tmp_9_fu_946_p3(0) = '1') else 
        tmp_22_cast_reg_1578;
    ref_tmp_i_i_i_0_1_1_fu_1230_p3 <= 
        select_ln75_7_fu_1223_p3 when (tmp_17_fu_1206_p3(0) = '1') else 
        tmp_46_cast_reg_1714;
    ref_tmp_i_i_i_0_1_fu_1100_p3 <= 
        select_ln75_5_fu_1093_p3 when (tmp_13_fu_1076_p3(0) = '1') else 
        tmp_34_cast_reg_1646;
    ref_tmp_i_i_i_0_fu_840_p3 <= 
        select_ln75_1_fu_833_p3 when (tmp_5_fu_816_p3(0) = '1') else 
        tmp_10_cast_reg_1510;
    select_ln74_1_fu_771_p3 <= 
        add_ln74_1_fu_766_p2 when (icmp_ln74_1_fu_761_p2(0) = '1') else 
        tmp_9_cast_reg_1476;
    select_ln74_2_fu_864_p3 <= 
        add_ln74_2_fu_859_p2 when (icmp_ln74_2_fu_854_p2(0) = '1') else 
        tmp_13_cast_reg_1527;
    select_ln74_3_fu_895_p3 <= 
        add_ln74_3_fu_890_p2 when (icmp_ln74_3_fu_885_p2(0) = '1') else 
        tmp_16_cast_reg_1544;
    select_ln74_4_fu_1000_p3 <= 
        add_ln74_7_fu_995_p2 when (icmp_ln74_4_fu_990_p2(0) = '1') else 
        tmp_25_cast_reg_1595;
    select_ln74_5_fu_1031_p3 <= 
        add_ln74_8_fu_1026_p2 when (icmp_ln74_5_fu_1021_p2(0) = '1') else 
        tmp_28_cast_reg_1612;
    select_ln74_6_fu_1124_p3 <= 
        add_ln74_9_fu_1119_p2 when (icmp_ln74_6_fu_1114_p2(0) = '1') else 
        tmp_37_cast_reg_1663;
    select_ln74_7_fu_1155_p3 <= 
        add_ln74_10_fu_1150_p2 when (icmp_ln74_7_fu_1145_p2(0) = '1') else 
        tmp_40_cast_reg_1680;
    select_ln74_fu_740_p3 <= 
        add_ln74_fu_735_p2 when (icmp_ln74_fu_730_p2(0) = '1') else 
        tmp_6_cast_reg_1459;
    select_ln75_1_fu_833_p3 <= 
        add_ln75_1_fu_828_p2 when (icmp_ln75_1_fu_823_p2(0) = '1') else 
        tmp_10_cast_reg_1510;
    select_ln75_2_fu_932_p3 <= 
        add_ln75_2_fu_927_p2 when (icmp_ln75_2_fu_922_p2(0) = '1') else 
        tmp_19_cast_reg_1561;
    select_ln75_3_fu_963_p3 <= 
        add_ln75_3_fu_958_p2 when (icmp_ln75_3_fu_953_p2(0) = '1') else 
        tmp_22_cast_reg_1578;
    select_ln75_4_fu_1062_p3 <= 
        add_ln75_5_fu_1057_p2 when (icmp_ln75_4_fu_1052_p2(0) = '1') else 
        tmp_31_cast_reg_1629;
    select_ln75_5_fu_1093_p3 <= 
        add_ln75_6_fu_1088_p2 when (icmp_ln75_5_fu_1083_p2(0) = '1') else 
        tmp_34_cast_reg_1646;
    select_ln75_6_fu_1192_p3 <= 
        add_ln75_7_fu_1187_p2 when (icmp_ln75_6_fu_1182_p2(0) = '1') else 
        tmp_43_cast_reg_1697;
    select_ln75_7_fu_1223_p3 <= 
        add_ln75_8_fu_1218_p2 when (icmp_ln75_7_fu_1213_p2(0) = '1') else 
        tmp_46_cast_reg_1714;
    select_ln75_fu_802_p3 <= 
        add_ln75_fu_797_p2 when (icmp_ln75_fu_792_p2(0) = '1') else 
        tmp_3_cast_reg_1493;
        sext_ln74_10_fu_637_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_re_3_reg_1444),32));

        sext_ln74_11_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_im_3_reg_1449),32));

        sext_ln74_1_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_re_reg_1414),32));

        sext_ln74_2_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_im_reg_1353_pp0_iter1_reg),32));

        sext_ln74_3_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_im_reg_1419),32));

        sext_ln74_4_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_re_1_reg_1364_pp0_iter1_reg),32));

        sext_ln74_5_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_re_1_reg_1424),32));

        sext_ln74_6_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_im_1_reg_1369_pp0_iter1_reg),32));

        sext_ln74_7_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_im_1_reg_1429),32));

        sext_ln74_8_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_re_2_reg_1434),32));

        sext_ln74_9_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_im_2_reg_1439),32));

        sext_ln74_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_re_reg_1348_pp0_iter1_reg),32));

    sub_ln75_2_fu_1237_p2 <= std_logic_vector(unsigned(ref_tmp_i_i84_i_0_1_fu_1069_p3) - unsigned(ref_tmp_i_i_i_0_1_fu_1100_p3));
    sub_ln75_fu_977_p2 <= std_logic_vector(unsigned(ref_tmp_i_i84_i_0_fu_809_p3) - unsigned(ref_tmp_i_i_i_0_fu_840_p3));
    tmp_10_fu_983_p3 <= mul_ln74_4_reg_1590(31 downto 31);
    tmp_11_fu_1014_p3 <= mul_ln74_5_reg_1607(31 downto 31);
    tmp_12_fu_1045_p3 <= mul_ln75_4_reg_1624(31 downto 31);
    tmp_13_fu_1076_p3 <= mul_ln75_5_reg_1641(31 downto 31);
    tmp_14_fu_1107_p3 <= mul_ln74_6_reg_1658(31 downto 31);
    tmp_15_fu_1138_p3 <= mul_ln74_7_reg_1675(31 downto 31);
    tmp_16_fu_1175_p3 <= mul_ln75_6_reg_1692(31 downto 31);
    tmp_17_fu_1206_p3 <= mul_ln75_7_reg_1709(31 downto 31);
    tmp_3_fu_754_p3 <= mul_ln74_1_reg_1471(31 downto 31);
    tmp_4_fu_785_p3 <= mul_ln75_reg_1488(31 downto 31);
    tmp_5_fu_816_p3 <= mul_ln75_1_reg_1505(31 downto 31);
    tmp_6_fu_847_p3 <= mul_ln74_2_reg_1522(31 downto 31);
    tmp_7_fu_878_p3 <= mul_ln74_3_reg_1539(31 downto 31);
    tmp_8_fu_915_p3 <= mul_ln75_2_reg_1556(31 downto 31);
    tmp_9_fu_946_p3 <= mul_ln75_3_reg_1573(31 downto 31);
    tmp_fu_723_p3 <= mul_ln74_reg_1454(31 downto 31);
    trunc_ln74_1_fu_415_p1 <= mul_ln74_1_fu_399_p2(14 - 1 downto 0);
    trunc_ln74_2_fu_481_p1 <= mul_ln74_2_fu_465_p2(14 - 1 downto 0);
    trunc_ln74_3_fu_507_p1 <= mul_ln74_3_fu_491_p2(14 - 1 downto 0);
    trunc_ln74_4_fu_570_p1 <= mul_ln74_4_fu_554_p2(14 - 1 downto 0);
    trunc_ln74_5_fu_593_p1 <= mul_ln74_5_fu_577_p2(14 - 1 downto 0);
    trunc_ln74_6_fu_656_p1 <= mul_ln74_6_fu_640_p2(14 - 1 downto 0);
    trunc_ln74_7_fu_679_p1 <= mul_ln74_7_fu_663_p2(14 - 1 downto 0);
    trunc_ln74_fu_389_p1 <= mul_ln74_fu_373_p2(14 - 1 downto 0);
    trunc_ln75_1_fu_455_p1 <= mul_ln75_1_fu_439_p2(14 - 1 downto 0);
    trunc_ln75_2_fu_527_p1 <= mul_ln75_2_fu_511_p2(14 - 1 downto 0);
    trunc_ln75_3_fu_547_p1 <= mul_ln75_3_fu_531_p2(14 - 1 downto 0);
    trunc_ln75_4_fu_613_p1 <= mul_ln75_4_fu_597_p2(14 - 1 downto 0);
    trunc_ln75_5_fu_633_p1 <= mul_ln75_5_fu_617_p2(14 - 1 downto 0);
    trunc_ln75_6_fu_699_p1 <= mul_ln75_6_fu_683_p2(14 - 1 downto 0);
    trunc_ln75_7_fu_719_p1 <= mul_ln75_7_fu_703_p2(14 - 1 downto 0);
    trunc_ln75_fu_435_p1 <= mul_ln75_fu_419_p2(14 - 1 downto 0);
    weights_im_1_address0 <= zext_ln137_fu_310_p1(10 - 1 downto 0);
    weights_im_1_ce0 <= weights_im_1_ce0_local;

    weights_im_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_im_1_ce0_local <= ap_const_logic_1;
        else 
            weights_im_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_im_2_address0 <= zext_ln137_fu_310_p1(10 - 1 downto 0);
    weights_im_2_ce0 <= weights_im_2_ce0_local;

    weights_im_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_im_2_ce0_local <= ap_const_logic_1;
        else 
            weights_im_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_im_3_address0 <= zext_ln137_fu_310_p1(10 - 1 downto 0);
    weights_im_3_ce0 <= weights_im_3_ce0_local;

    weights_im_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_im_3_ce0_local <= ap_const_logic_1;
        else 
            weights_im_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_im_address0 <= zext_ln137_fu_310_p1(10 - 1 downto 0);
    weights_im_ce0 <= weights_im_ce0_local;

    weights_im_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_im_ce0_local <= ap_const_logic_1;
        else 
            weights_im_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_re_1_address0 <= zext_ln137_fu_310_p1(10 - 1 downto 0);
    weights_re_1_ce0 <= weights_re_1_ce0_local;

    weights_re_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_re_1_ce0_local <= ap_const_logic_1;
        else 
            weights_re_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_re_2_address0 <= zext_ln137_fu_310_p1(10 - 1 downto 0);
    weights_re_2_ce0 <= weights_re_2_ce0_local;

    weights_re_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_re_2_ce0_local <= ap_const_logic_1;
        else 
            weights_re_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_re_3_address0 <= zext_ln137_fu_310_p1(10 - 1 downto 0);
    weights_re_3_ce0 <= weights_re_3_ce0_local;

    weights_re_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_re_3_ce0_local <= ap_const_logic_1;
        else 
            weights_re_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_re_address0 <= zext_ln137_fu_310_p1(10 - 1 downto 0);
    weights_re_ce0 <= weights_re_ce0_local;

    weights_re_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_re_ce0_local <= ap_const_logic_1;
        else 
            weights_re_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    x_re_1_fu_348_p1 <= in_stream_1_TDATA(16 - 1 downto 0);
    x_re_fu_326_p1 <= in_stream_0_TDATA(16 - 1 downto 0);
    zext_ln137_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_1),64));
end behav;
