// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module snr_monitor_top_snr_monitor_top_Pipeline_pilot_snr (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fft_re_address0,
        fft_re_ce0,
        fft_re_q0,
        fft_im_address0,
        fft_im_ce0,
        fft_im_q0,
        h_re_address0,
        h_re_ce0,
        h_re_q0,
        h_im_address0,
        h_im_ce0,
        h_im_q0,
        nse_pow_out,
        nse_pow_out_ap_vld,
        sig_pow_out,
        sig_pow_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] fft_re_address0;
output   fft_re_ce0;
input  [15:0] fft_re_q0;
output  [9:0] fft_im_address0;
output   fft_im_ce0;
input  [15:0] fft_im_q0;
output  [9:0] h_re_address0;
output   h_re_ce0;
input  [15:0] h_re_q0;
output  [9:0] h_im_address0;
output   h_im_ce0;
input  [15:0] h_im_q0;
output  [38:0] nse_pow_out;
output   nse_pow_out_ap_vld;
output  [38:0] sig_pow_out;
output   sig_pow_out_ap_vld;

reg ap_idle;
reg nse_pow_out_ap_vld;
reg sig_pow_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln119_fu_184_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] DMRS_RE_address0;
wire   [14:0] DMRS_RE_q0;
wire   [6:0] DMRS_IM_address0;
wire   [14:0] DMRS_IM_q0;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] m_1_reg_436;
reg   [0:0] icmp_ln119_reg_443;
reg   [0:0] icmp_ln119_reg_443_pp0_iter1_reg;
reg   [0:0] icmp_ln119_reg_443_pp0_iter2_reg;
reg   [0:0] icmp_ln119_reg_443_pp0_iter3_reg;
reg   [0:0] icmp_ln119_reg_443_pp0_iter4_reg;
reg   [0:0] icmp_ln119_reg_443_pp0_iter5_reg;
reg   [0:0] icmp_ln119_reg_443_pp0_iter6_reg;
reg   [0:0] icmp_ln119_reg_443_pp0_iter7_reg;
wire   [63:0] zext_ln130_fu_236_p1;
reg   [63:0] zext_ln130_reg_447;
reg   [63:0] zext_ln130_reg_447_pp0_iter2_reg;
reg   [63:0] zext_ln130_reg_447_pp0_iter3_reg;
reg   [63:0] zext_ln130_reg_447_pp0_iter4_reg;
reg   [14:0] x_re_reg_473;
wire  signed [29:0] sext_ln145_fu_242_p1;
reg  signed [29:0] sext_ln145_reg_478;
wire  signed [29:0] sext_ln145_2_fu_246_p1;
reg  signed [29:0] sext_ln145_2_reg_484;
wire  signed [29:0] sext_ln145_3_fu_250_p1;
wire   [29:0] mul_ln145_fu_257_p2;
reg  signed [29:0] mul_ln145_reg_496;
wire   [29:0] mul_ln146_1_fu_262_p2;
reg  signed [29:0] mul_ln146_1_reg_501;
reg   [15:0] y_im_reg_516;
reg  signed [15:0] s_re_reg_521;
reg  signed [15:0] s_re_reg_521_pp0_iter6_reg;
reg  signed [15:0] s_im_reg_527;
wire   [15:0] e_re_fu_297_p2;
reg   [15:0] e_re_reg_533;
wire  signed [31:0] sext_ln156_2_fu_306_p1;
wire  signed [31:0] sext_ln157_2_fu_309_p1;
wire   [31:0] mul_ln156_fu_316_p2;
reg  signed [31:0] mul_ln156_reg_550;
wire   [31:0] mul_ln157_fu_325_p2;
reg  signed [31:0] mul_ln157_reg_555;
wire   [63:0] zext_ln119_fu_201_p1;
wire    ap_block_pp0_stage0;
reg   [38:0] sig_pow_fu_62;
wire   [38:0] sig_pow_1_fu_346_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [38:0] nse_pow_fu_66;
wire   [38:0] nse_pow_1_fu_355_p2;
reg   [6:0] m_fu_70;
wire   [6:0] m_2_fu_190_p2;
reg   [6:0] ap_sig_allocacmp_m_1;
wire    ap_block_pp0_stage0_01001;
reg    DMRS_RE_ce0_local;
reg    DMRS_IM_ce0_local;
reg    h_re_ce0_local;
reg    h_im_ce0_local;
reg    fft_im_ce0_local;
reg    fft_re_ce0_local;
wire   [7:0] tmp_fu_213_p3;
wire   [9:0] p_shl_fu_206_p3;
wire   [9:0] zext_ln123_fu_220_p1;
wire   [9:0] sub_ln123_fu_224_p2;
wire   [9:0] k_fu_230_p2;
wire  signed [15:0] mul_ln145_fu_257_p0;
wire  signed [14:0] mul_ln145_fu_257_p1;
wire  signed [29:0] sext_ln145_1_fu_254_p1;
wire  signed [15:0] mul_ln146_1_fu_262_p0;
wire  signed [14:0] mul_ln146_1_fu_262_p1;
wire  signed [29:0] grp_fu_379_p3;
(* use_dsp48 = "no" *) wire   [29:0] add_ln147_fu_267_p2;
wire  signed [29:0] grp_fu_387_p3;
(* use_dsp48 = "no" *) wire   [29:0] add_ln148_fu_282_p2;
wire   [15:0] e_im_fu_302_p2;
wire  signed [15:0] mul_ln156_fu_316_p0;
wire  signed [31:0] sext_ln156_fu_313_p1;
wire  signed [15:0] mul_ln156_fu_316_p1;
wire  signed [15:0] mul_ln157_fu_325_p0;
wire  signed [31:0] sext_ln157_fu_322_p1;
wire  signed [15:0] mul_ln157_fu_325_p1;
wire  signed [32:0] grp_fu_395_p3;
wire  signed [38:0] sext_ln156_4_fu_343_p1;
wire  signed [32:0] grp_fu_404_p3;
wire  signed [38:0] sext_ln157_4_fu_352_p1;
wire  signed [14:0] grp_fu_379_p1;
wire  signed [14:0] grp_fu_387_p1;
wire  signed [15:0] grp_fu_395_p0;
wire  signed [15:0] grp_fu_395_p1;
wire  signed [15:0] grp_fu_404_p0;
wire  signed [15:0] grp_fu_404_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 sig_pow_fu_62 = 39'd0;
#0 nse_pow_fu_66 = 39'd0;
#0 m_fu_70 = 7'd0;
#0 ap_done_reg = 1'b0;
end

snr_monitor_top_snr_monitor_top_Pipeline_pilot_snr_DMRS_RE_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
DMRS_RE_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DMRS_RE_address0),
    .ce0(DMRS_RE_ce0_local),
    .q0(DMRS_RE_q0)
);

snr_monitor_top_snr_monitor_top_Pipeline_pilot_snr_DMRS_IM_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
DMRS_IM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DMRS_IM_address0),
    .ce0(DMRS_IM_ce0_local),
    .q0(DMRS_IM_q0)
);

snr_monitor_top_mul_16s_15s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_16s_15s_30_1_1_U17(
    .din0(mul_ln145_fu_257_p0),
    .din1(mul_ln145_fu_257_p1),
    .dout(mul_ln145_fu_257_p2)
);

snr_monitor_top_mul_16s_15s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_16s_15s_30_1_1_U18(
    .din0(mul_ln146_1_fu_262_p0),
    .din1(mul_ln146_1_fu_262_p1),
    .dout(mul_ln146_1_fu_262_p2)
);

snr_monitor_top_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U19(
    .din0(mul_ln156_fu_316_p0),
    .din1(mul_ln156_fu_316_p1),
    .dout(mul_ln156_fu_316_p2)
);

snr_monitor_top_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U20(
    .din0(mul_ln157_fu_325_p0),
    .din1(mul_ln157_fu_325_p1),
    .dout(mul_ln157_fu_325_p2)
);

snr_monitor_top_mac_mulsub_16s_15s_30s_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mac_mulsub_16s_15s_30s_30_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(h_im_q0),
    .din1(grp_fu_379_p1),
    .din2(mul_ln145_reg_496),
    .ce(1'b1),
    .dout(grp_fu_379_p3)
);

snr_monitor_top_mac_muladd_16s_15s_30s_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mac_muladd_16s_15s_30s_30_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(h_re_q0),
    .din1(grp_fu_387_p1),
    .din2(mul_ln146_1_reg_501),
    .ce(1'b1),
    .dout(grp_fu_387_p3)
);

snr_monitor_top_mac_muladd_16s_16s_32s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 33 ))
mac_muladd_16s_16s_32s_33_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_395_p0),
    .din1(grp_fu_395_p1),
    .din2(mul_ln156_reg_550),
    .ce(1'b1),
    .dout(grp_fu_395_p3)
);

snr_monitor_top_mac_muladd_16s_16s_32s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 33 ))
mac_muladd_16s_16s_32s_33_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_404_p0),
    .din1(grp_fu_404_p1),
    .din2(mul_ln157_reg_555),
    .ce(1'b1),
    .dout(grp_fu_404_p3)
);

snr_monitor_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln119_fu_184_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            m_fu_70 <= m_2_fu_190_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            m_fu_70 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            nse_pow_fu_66 <= 39'd0;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            nse_pow_fu_66 <= nse_pow_1_fu_355_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sig_pow_fu_62 <= 39'd0;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            sig_pow_fu_62 <= sig_pow_1_fu_346_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln119_reg_443 <= icmp_ln119_fu_184_p2;
        icmp_ln119_reg_443_pp0_iter1_reg <= icmp_ln119_reg_443;
        m_1_reg_436 <= ap_sig_allocacmp_m_1;
        zext_ln130_reg_447[9 : 1] <= zext_ln130_fu_236_p1[9 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        e_re_reg_533 <= e_re_fu_297_p2;
        icmp_ln119_reg_443_pp0_iter2_reg <= icmp_ln119_reg_443_pp0_iter1_reg;
        icmp_ln119_reg_443_pp0_iter3_reg <= icmp_ln119_reg_443_pp0_iter2_reg;
        icmp_ln119_reg_443_pp0_iter4_reg <= icmp_ln119_reg_443_pp0_iter3_reg;
        icmp_ln119_reg_443_pp0_iter5_reg <= icmp_ln119_reg_443_pp0_iter4_reg;
        icmp_ln119_reg_443_pp0_iter6_reg <= icmp_ln119_reg_443_pp0_iter5_reg;
        icmp_ln119_reg_443_pp0_iter7_reg <= icmp_ln119_reg_443_pp0_iter6_reg;
        mul_ln145_reg_496 <= mul_ln145_fu_257_p2;
        mul_ln146_1_reg_501 <= mul_ln146_1_fu_262_p2;
        mul_ln156_reg_550 <= mul_ln156_fu_316_p2;
        mul_ln157_reg_555 <= mul_ln157_fu_325_p2;
        s_im_reg_527 <= {{add_ln148_fu_282_p2[29:14]}};
        s_re_reg_521 <= {{add_ln147_fu_267_p2[29:14]}};
        s_re_reg_521_pp0_iter6_reg <= s_re_reg_521;
        sext_ln145_2_reg_484 <= sext_ln145_2_fu_246_p1;
        sext_ln145_reg_478 <= sext_ln145_fu_242_p1;
        x_re_reg_473 <= DMRS_RE_q0;
        y_im_reg_516 <= fft_im_q0;
        zext_ln130_reg_447_pp0_iter2_reg[9 : 1] <= zext_ln130_reg_447[9 : 1];
        zext_ln130_reg_447_pp0_iter3_reg[9 : 1] <= zext_ln130_reg_447_pp0_iter2_reg[9 : 1];
        zext_ln130_reg_447_pp0_iter4_reg[9 : 1] <= zext_ln130_reg_447_pp0_iter3_reg[9 : 1];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DMRS_IM_ce0_local = 1'b1;
    end else begin
        DMRS_IM_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DMRS_RE_ce0_local = 1'b1;
    end else begin
        DMRS_RE_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln119_fu_184_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_m_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_m_1 = m_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        fft_im_ce0_local = 1'b1;
    end else begin
        fft_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        fft_re_ce0_local = 1'b1;
    end else begin
        fft_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        h_im_ce0_local = 1'b1;
    end else begin
        h_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        h_re_ce0_local = 1'b1;
    end else begin
        h_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (icmp_ln119_reg_443_pp0_iter7_reg == 1'd1))) begin
        nse_pow_out_ap_vld = 1'b1;
    end else begin
        nse_pow_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (icmp_ln119_reg_443_pp0_iter7_reg == 1'd1))) begin
        sig_pow_out_ap_vld = 1'b1;
    end else begin
        sig_pow_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DMRS_IM_address0 = zext_ln119_fu_201_p1;

assign DMRS_RE_address0 = zext_ln119_fu_201_p1;

assign add_ln147_fu_267_p2 = ($signed(grp_fu_379_p3) + $signed(30'd8192));

assign add_ln148_fu_282_p2 = ($signed(grp_fu_387_p3) + $signed(30'd8192));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign e_im_fu_302_p2 = ($signed(y_im_reg_516) - $signed(s_im_reg_527));

assign e_re_fu_297_p2 = ($signed(fft_re_q0) - $signed(s_re_reg_521));

assign fft_im_address0 = zext_ln130_reg_447_pp0_iter3_reg;

assign fft_im_ce0 = fft_im_ce0_local;

assign fft_re_address0 = zext_ln130_reg_447_pp0_iter4_reg;

assign fft_re_ce0 = fft_re_ce0_local;

assign grp_fu_379_p1 = sext_ln145_3_fu_250_p1;

assign grp_fu_387_p1 = sext_ln145_3_fu_250_p1;

assign grp_fu_395_p0 = sext_ln156_2_fu_306_p1;

assign grp_fu_395_p1 = sext_ln156_2_fu_306_p1;

assign grp_fu_404_p0 = sext_ln157_2_fu_309_p1;

assign grp_fu_404_p1 = sext_ln157_2_fu_309_p1;

assign h_im_address0 = zext_ln130_fu_236_p1;

assign h_im_ce0 = h_im_ce0_local;

assign h_re_address0 = zext_ln130_fu_236_p1;

assign h_re_ce0 = h_re_ce0_local;

assign icmp_ln119_fu_184_p2 = ((ap_sig_allocacmp_m_1 == 7'd100) ? 1'b1 : 1'b0);

assign k_fu_230_p2 = (sub_ln123_fu_224_p2 + 10'd213);

assign m_2_fu_190_p2 = (ap_sig_allocacmp_m_1 + 7'd1);

assign mul_ln145_fu_257_p0 = sext_ln145_reg_478;

assign mul_ln145_fu_257_p1 = sext_ln145_1_fu_254_p1;

assign mul_ln146_1_fu_262_p0 = sext_ln145_2_reg_484;

assign mul_ln146_1_fu_262_p1 = sext_ln145_1_fu_254_p1;

assign mul_ln156_fu_316_p0 = sext_ln156_fu_313_p1;

assign mul_ln156_fu_316_p1 = sext_ln156_fu_313_p1;

assign mul_ln157_fu_325_p0 = sext_ln157_fu_322_p1;

assign mul_ln157_fu_325_p1 = sext_ln157_fu_322_p1;

assign nse_pow_1_fu_355_p2 = ($signed(nse_pow_fu_66) + $signed(sext_ln157_4_fu_352_p1));

assign nse_pow_out = nse_pow_fu_66;

assign p_shl_fu_206_p3 = {{m_1_reg_436}, {3'd0}};

assign sext_ln145_1_fu_254_p1 = $signed(x_re_reg_473);

assign sext_ln145_2_fu_246_p1 = $signed(h_im_q0);

assign sext_ln145_3_fu_250_p1 = $signed(DMRS_IM_q0);

assign sext_ln145_fu_242_p1 = $signed(h_re_q0);

assign sext_ln156_2_fu_306_p1 = s_im_reg_527;

assign sext_ln156_4_fu_343_p1 = grp_fu_395_p3;

assign sext_ln156_fu_313_p1 = s_re_reg_521_pp0_iter6_reg;

assign sext_ln157_2_fu_309_p1 = $signed(e_im_fu_302_p2);

assign sext_ln157_4_fu_352_p1 = grp_fu_404_p3;

assign sext_ln157_fu_322_p1 = $signed(e_re_reg_533);

assign sig_pow_1_fu_346_p2 = ($signed(sig_pow_fu_62) + $signed(sext_ln156_4_fu_343_p1));

assign sig_pow_out = sig_pow_fu_62;

assign sub_ln123_fu_224_p2 = (p_shl_fu_206_p3 - zext_ln123_fu_220_p1);

assign tmp_fu_213_p3 = {{m_1_reg_436}, {1'd0}};

assign zext_ln119_fu_201_p1 = m_1_reg_436;

assign zext_ln123_fu_220_p1 = tmp_fu_213_p3;

assign zext_ln130_fu_236_p1 = k_fu_230_p2;

always @ (posedge ap_clk) begin
    zext_ln130_reg_447[0] <= 1'b1;
    zext_ln130_reg_447[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln130_reg_447_pp0_iter2_reg[0] <= 1'b1;
    zext_ln130_reg_447_pp0_iter2_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln130_reg_447_pp0_iter3_reg[0] <= 1'b1;
    zext_ln130_reg_447_pp0_iter3_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln130_reg_447_pp0_iter4_reg[0] <= 1'b1;
    zext_ln130_reg_447_pp0_iter4_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //snr_monitor_top_snr_monitor_top_Pipeline_pilot_snr
