// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cp_insertion_cp_insertion_Pipeline_cp_out (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_stream_TREADY,
        buf_data_address0,
        buf_data_ce0,
        buf_data_q0,
        buf_data_1_address0,
        buf_data_1_ce0,
        buf_data_1_q0,
        buf_data_2_address0,
        buf_data_2_ce0,
        buf_data_2_q0,
        buf_data_3_address0,
        buf_data_3_ce0,
        buf_data_3_q0,
        buf_strb_address0,
        buf_strb_ce0,
        buf_strb_q0,
        buf_strb_1_address0,
        buf_strb_1_ce0,
        buf_strb_1_q0,
        buf_strb_2_address0,
        buf_strb_2_ce0,
        buf_strb_2_q0,
        buf_strb_3_address0,
        buf_strb_3_ce0,
        buf_strb_3_q0,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_stream_TREADY;
output  [7:0] buf_data_address0;
output   buf_data_ce0;
input  [31:0] buf_data_q0;
output  [7:0] buf_data_1_address0;
output   buf_data_1_ce0;
input  [31:0] buf_data_1_q0;
output  [7:0] buf_data_2_address0;
output   buf_data_2_ce0;
input  [31:0] buf_data_2_q0;
output  [7:0] buf_data_3_address0;
output   buf_data_3_ce0;
input  [31:0] buf_data_3_q0;
output  [7:0] buf_strb_address0;
output   buf_strb_ce0;
input  [3:0] buf_strb_q0;
output  [7:0] buf_strb_1_address0;
output   buf_strb_1_ce0;
input  [3:0] buf_strb_1_q0;
output  [7:0] buf_strb_2_address0;
output   buf_strb_2_ce0;
input  [3:0] buf_strb_2_q0;
output  [7:0] buf_strb_3_address0;
output   buf_strb_3_ce0;
input  [3:0] buf_strb_3_q0;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;

reg ap_idle;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln66_fu_226_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg   [7:0] i_reg_336;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln66_fu_243_p1;
reg   [1:0] trunc_ln66_reg_346;
wire   [63:0] zext_ln69_1_fu_269_p1;
reg   [7:0] i_1_fu_92;
wire   [7:0] add_ln66_fu_232_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i;
wire   [31:0] s_data_fu_281_p11;
reg    ap_block_pp0_stage0_01001;
wire   [3:0] s_strb_fu_305_p11;
reg    buf_data_ce0_local;
reg    buf_data_1_ce0_local;
reg    buf_data_2_ce0_local;
reg    buf_data_3_ce0_local;
reg    buf_strb_ce0_local;
reg    buf_strb_1_ce0_local;
reg    buf_strb_2_ce0_local;
reg    buf_strb_3_ce0_local;
wire   [5:0] tmp_fu_246_p4;
wire   [6:0] zext_ln69_fu_255_p1;
wire   [6:0] add_ln69_fu_259_p2;
wire  signed [7:0] sext_ln69_fu_265_p1;
wire   [31:0] s_data_fu_281_p9;
wire   [3:0] s_strb_fu_305_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] s_data_fu_281_p1;
wire   [1:0] s_data_fu_281_p3;
wire  signed [1:0] s_data_fu_281_p5;
wire  signed [1:0] s_data_fu_281_p7;
wire   [1:0] s_strb_fu_305_p1;
wire   [1:0] s_strb_fu_305_p3;
wire  signed [1:0] s_strb_fu_305_p5;
wire  signed [1:0] s_strb_fu_305_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_1_fu_92 = 8'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) cp_insertion_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U13(
    .din0(buf_data_q0),
    .din1(buf_data_1_q0),
    .din2(buf_data_2_q0),
    .din3(buf_data_3_q0),
    .def(s_data_fu_281_p9),
    .sel(trunc_ln66_reg_346),
    .dout(s_data_fu_281_p11)
);

(* dissolve_hierarchy = "yes" *) cp_insertion_sparsemux_9_2_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 4 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 4 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 4 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
sparsemux_9_2_4_1_1_U14(
    .din0(buf_strb_q0),
    .din1(buf_strb_1_q0),
    .din2(buf_strb_2_q0),
    .din3(buf_strb_3_q0),
    .def(s_strb_fu_305_p9),
    .sel(trunc_ln66_reg_346),
    .dout(s_strb_fu_305_p11)
);

cp_insertion_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln66_fu_226_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_92 <= add_ln66_fu_232_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_92 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_reg_336 <= ap_sig_allocacmp_i;
        trunc_ln66_reg_346 <= trunc_ln66_fu_243_p1;
    end
end

always @ (*) begin
    if (((icmp_ln66_fu_226_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 8'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_data_1_ce0_local = 1'b1;
    end else begin
        buf_data_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_data_2_ce0_local = 1'b1;
    end else begin
        buf_data_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_data_3_ce0_local = 1'b1;
    end else begin
        buf_data_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_data_ce0_local = 1'b1;
    end else begin
        buf_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_strb_1_ce0_local = 1'b1;
    end else begin
        buf_strb_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_strb_2_ce0_local = 1'b1;
    end else begin
        buf_strb_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_strb_3_ce0_local = 1'b1;
    end else begin
        buf_strb_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_strb_ce0_local = 1'b1;
    end else begin
        buf_strb_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln66_fu_232_p2 = (ap_sig_allocacmp_i + 8'd1);

assign add_ln69_fu_259_p2 = ($signed(zext_ln69_fu_255_p1) + $signed(7'd92));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((out_stream_TREADY == 1'b0) | (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((out_stream_TREADY == 1'b0) | (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (out_stream_TREADY == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buf_data_1_address0 = zext_ln69_1_fu_269_p1;

assign buf_data_1_ce0 = buf_data_1_ce0_local;

assign buf_data_2_address0 = zext_ln69_1_fu_269_p1;

assign buf_data_2_ce0 = buf_data_2_ce0_local;

assign buf_data_3_address0 = zext_ln69_1_fu_269_p1;

assign buf_data_3_ce0 = buf_data_3_ce0_local;

assign buf_data_address0 = zext_ln69_1_fu_269_p1;

assign buf_data_ce0 = buf_data_ce0_local;

assign buf_strb_1_address0 = zext_ln69_1_fu_269_p1;

assign buf_strb_1_ce0 = buf_strb_1_ce0_local;

assign buf_strb_2_address0 = zext_ln69_1_fu_269_p1;

assign buf_strb_2_ce0 = buf_strb_2_ce0_local;

assign buf_strb_3_address0 = zext_ln69_1_fu_269_p1;

assign buf_strb_3_ce0 = buf_strb_3_ce0_local;

assign buf_strb_address0 = zext_ln69_1_fu_269_p1;

assign buf_strb_ce0 = buf_strb_ce0_local;

assign icmp_ln66_fu_226_p2 = ((ap_sig_allocacmp_i == 8'd144) ? 1'b1 : 1'b0);

assign out_stream_TDATA = s_data_fu_281_p11;

assign out_stream_TKEEP = 4'd15;

assign out_stream_TLAST = 1'd0;

assign out_stream_TSTRB = s_strb_fu_305_p11;

assign s_data_fu_281_p9 = 'bx;

assign s_strb_fu_305_p9 = 'bx;

assign sext_ln69_fu_265_p1 = $signed(add_ln69_fu_259_p2);

assign tmp_fu_246_p4 = {{i_reg_336[7:2]}};

assign trunc_ln66_fu_243_p1 = i_reg_336[1:0];

assign zext_ln69_1_fu_269_p1 = $unsigned(sext_ln69_fu_265_p1);

assign zext_ln69_fu_255_p1 = tmp_fu_246_p4;

endmodule //cp_insertion_cp_insertion_Pipeline_cp_out
