// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_top_process_phase_Pipeline_VITIS_LOOP_44_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        coeff_stream_dout,
        coeff_stream_num_data_valid,
        coeff_stream_fifo_cap,
        coeff_stream_empty_n,
        coeff_stream_read,
        result_stream_din,
        result_stream_num_data_valid,
        result_stream_fifo_cap,
        result_stream_full_n,
        result_stream_write,
        mode_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] coeff_stream_dout;
input  [8:0] coeff_stream_num_data_valid;
input  [8:0] coeff_stream_fifo_cap;
input   coeff_stream_empty_n;
output   coeff_stream_read;
output  [15:0] result_stream_din;
input  [8:0] result_stream_num_data_valid;
input  [8:0] result_stream_fifo_cap;
input   result_stream_full_n;
output   result_stream_write;
input  [31:0] mode_1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln44_fu_118_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    coeff_stream_blk_n;
wire    ap_block_pp0_stage0;
reg    result_stream_blk_n;
reg    ap_block_pp0_stage0_11001;
reg  signed [15:0] val_reg_234;
reg  signed [15:0] val_reg_234_pp0_iter1_reg;
wire   [28:0] a_2_fu_135_p2;
reg   [28:0] a_2_reg_250;
reg   [28:0] a_2_reg_250_pp0_iter2_reg;
reg   [28:0] a_2_reg_250_pp0_iter3_reg;
reg  signed [28:0] a_2_reg_250_pp0_iter4_reg;
wire  signed [15:0] trunc_ln51_1_fu_141_p1;
reg  signed [15:0] trunc_ln51_1_reg_255;
wire  signed [27:0] a_1_fu_145_p2;
reg  signed [27:0] a_1_reg_260;
reg  signed [27:0] a_1_reg_260_pp0_iter2_reg;
reg  signed [27:0] a_1_reg_260_pp0_iter3_reg;
reg  signed [27:0] a_1_reg_260_pp0_iter4_reg;
wire  signed [15:0] trunc_ln51_fu_151_p1;
reg  signed [15:0] trunc_ln51_reg_265;
wire   [15:0] u_2_fu_155_p2;
reg  signed [15:0] u_2_reg_270;
wire   [15:0] u_1_fu_160_p2;
reg  signed [15:0] u_1_reg_275;
wire  signed [28:0] grp_fu_200_p3;
wire  signed [28:0] grp_fu_208_p3;
wire  signed [28:0] grp_fu_215_p3;
wire   [28:0] ap_phi_reg_pp0_iter0_result_1_in_in_reg_83;
reg   [28:0] ap_phi_reg_pp0_iter1_result_1_in_in_reg_83;
reg   [28:0] ap_phi_reg_pp0_iter2_result_1_in_in_reg_83;
reg   [28:0] ap_phi_reg_pp0_iter3_result_1_in_in_reg_83;
reg   [28:0] ap_phi_reg_pp0_iter4_result_1_in_in_reg_83;
reg   [28:0] ap_phi_reg_pp0_iter5_result_1_in_in_reg_83;
reg   [28:0] ap_phi_reg_pp0_iter6_result_1_in_in_reg_83;
reg   [28:0] ap_phi_reg_pp0_iter7_result_1_in_in_reg_83;
reg    ap_predicate_pred178_state7;
reg    ap_predicate_pred184_state7;
reg    ap_predicate_pred190_state4;
reg   [7:0] i1_fu_60;
wire   [7:0] i_fu_102_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i1_load;
reg    coeff_stream_read_local;
wire  signed [15:0] sext_ln53_fu_195_p1;
reg    ap_block_pp0_stage0_01001;
reg    result_stream_write_local;
wire  signed [15:0] u_fu_108_p0;
wire  signed [15:0] u_fu_108_p2;
wire   [12:0] a_2_fu_135_p1;
wire   [11:0] a_1_fu_145_p1;
wire  signed [12:0] u_2_fu_155_p1;
wire  signed [12:0] u_1_fu_160_p1;
wire  signed [25:0] a_fu_165_p3;
wire   [12:0] result_fu_185_p4;
wire  signed [12:0] grp_fu_200_p1;
wire  signed [12:0] grp_fu_208_p1;
wire  signed [12:0] grp_fu_215_p1;
reg    grp_fu_200_ce;
reg    grp_fu_208_ce;
reg    grp_fu_215_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 i1_fu_60 = 8'd0;
#0 ap_done_reg = 1'b0;
end

mlkem_top_mul_16s_13ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mul_16s_13ns_29_1_1_U17(
    .din0(val_reg_234),
    .din1(a_2_fu_135_p1),
    .dout(a_2_fu_135_p2)
);

mlkem_top_mul_16s_12ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12ns_28_1_1_U18(
    .din0(val_reg_234),
    .din1(a_1_fu_145_p1),
    .dout(a_1_fu_145_p2)
);

mlkem_top_mul_16s_13s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mul_16s_13s_16_1_1_U19(
    .din0(trunc_ln51_1_reg_255),
    .din1(u_2_fu_155_p1),
    .dout(u_2_fu_155_p2)
);

mlkem_top_mul_16s_13s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mul_16s_13s_16_1_1_U20(
    .din0(trunc_ln51_reg_265),
    .din1(u_1_fu_160_p1),
    .dout(u_1_fu_160_p2)
);

mlkem_top_mac_muladd_16s_13s_26s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_13s_26s_29_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(u_fu_108_p2),
    .din1(grp_fu_200_p1),
    .din2(a_fu_165_p3),
    .ce(grp_fu_200_ce),
    .dout(grp_fu_200_p3)
);

mlkem_top_mac_muladd_16s_13s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_13s_29s_29_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(u_2_reg_270),
    .din1(grp_fu_208_p1),
    .din2(a_2_reg_250_pp0_iter4_reg),
    .ce(grp_fu_208_ce),
    .dout(grp_fu_208_p3)
);

mlkem_top_mac_muladd_16s_13s_28s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_13s_28s_29_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(u_1_reg_275),
    .din1(grp_fu_215_p1),
    .din2(a_1_reg_260_pp0_iter4_reg),
    .ce(grp_fu_215_ce),
    .dout(grp_fu_215_p3)
);

mlkem_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((ap_predicate_pred190_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_result_1_in_in_reg_83 <= grp_fu_200_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_result_1_in_in_reg_83 <= ap_phi_reg_pp0_iter3_result_1_in_in_reg_83;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        if ((ap_predicate_pred184_state7 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_result_1_in_in_reg_83 <= grp_fu_208_p3;
        end else if ((ap_predicate_pred178_state7 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_result_1_in_in_reg_83 <= grp_fu_215_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_result_1_in_in_reg_83 <= ap_phi_reg_pp0_iter6_result_1_in_in_reg_83;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_start_int == 1'b1)) begin
            i1_fu_60 <= i_fu_102_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i1_fu_60 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_reg_260 <= a_1_fu_145_p2;
        a_2_reg_250 <= a_2_fu_135_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln51_1_reg_255 <= trunc_ln51_1_fu_141_p1;
        trunc_ln51_reg_265 <= trunc_ln51_fu_151_p1;
        val_reg_234 <= coeff_stream_dout;
        val_reg_234_pp0_iter1_reg <= val_reg_234;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a_1_reg_260_pp0_iter2_reg <= a_1_reg_260;
        a_1_reg_260_pp0_iter3_reg <= a_1_reg_260_pp0_iter2_reg;
        a_1_reg_260_pp0_iter4_reg <= a_1_reg_260_pp0_iter3_reg;
        a_2_reg_250_pp0_iter2_reg <= a_2_reg_250;
        a_2_reg_250_pp0_iter3_reg <= a_2_reg_250_pp0_iter2_reg;
        a_2_reg_250_pp0_iter4_reg <= a_2_reg_250_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_predicate_pred178_state7 <= (mode_1 == 32'd0);
        ap_predicate_pred184_state7 <= (mode_1 == 32'd1);
        ap_predicate_pred190_state4 <= (~(mode_1 == 32'd1) & ~(mode_1 == 32'd0));
        u_1_reg_275 <= u_1_fu_160_p2;
        u_2_reg_270 <= u_2_fu_155_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_result_1_in_in_reg_83 <= ap_phi_reg_pp0_iter0_result_1_in_in_reg_83;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_result_1_in_in_reg_83 <= ap_phi_reg_pp0_iter1_result_1_in_in_reg_83;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_result_1_in_in_reg_83 <= ap_phi_reg_pp0_iter2_result_1_in_in_reg_83;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_result_1_in_in_reg_83 <= ap_phi_reg_pp0_iter4_result_1_in_in_reg_83;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_result_1_in_in_reg_83 <= ap_phi_reg_pp0_iter5_result_1_in_in_reg_83;
    end
end

always @ (*) begin
    if (((icmp_ln44_fu_118_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i1_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        coeff_stream_blk_n = coeff_stream_empty_n;
    end else begin
        coeff_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        coeff_stream_read_local = 1'b1;
    end else begin
        coeff_stream_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_200_ce = 1'b1;
    end else begin
        grp_fu_200_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_208_ce = 1'b1;
    end else begin
        grp_fu_208_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_215_ce = 1'b1;
    end else begin
        grp_fu_215_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        result_stream_blk_n = result_stream_full_n;
    end else begin
        result_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        result_stream_write_local = 1'b1;
    end else begin
        result_stream_write_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_1_fu_145_p1 = 28'd1353;

assign a_2_fu_135_p1 = 29'd2285;

assign a_fu_165_p3 = {{val_reg_234_pp0_iter1_reg}, {10'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (coeff_stream_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = (result_stream_full_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_result_1_in_in_reg_83 = 'bx;

assign ap_ready = ap_ready_sig;

assign coeff_stream_read = coeff_stream_read_local;

assign grp_fu_200_p1 = 29'd536867583;

assign grp_fu_208_p1 = 29'd536867583;

assign grp_fu_215_p1 = 29'd536867583;

assign i_fu_102_p2 = (ap_sig_allocacmp_i1_load + 8'd1);

assign icmp_ln44_fu_118_p2 = ((ap_sig_allocacmp_i1_load == 8'd255) ? 1'b1 : 1'b0);

assign result_fu_185_p4 = {{ap_phi_reg_pp0_iter7_result_1_in_in_reg_83[28:16]}};

assign result_stream_din = sext_ln53_fu_195_p1;

assign result_stream_write = result_stream_write_local;

assign sext_ln53_fu_195_p1 = $signed(result_fu_185_p4);

assign trunc_ln51_1_fu_141_p1 = a_2_fu_135_p2[15:0];

assign trunc_ln51_fu_151_p1 = a_1_fu_145_p2[15:0];

assign u_1_fu_160_p1 = 16'd62209;

assign u_2_fu_155_p1 = 16'd62209;

assign u_fu_108_p0 = coeff_stream_dout;

assign u_fu_108_p2 = u_fu_108_p0 << 16'd10;

endmodule //mlkem_top_process_phase_Pipeline_VITIS_LOOP_44_1
