

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_phase_U0"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_phase_U0.grp_read_phase_Pipeline_VITIS_LOOP_30_1_fu_52"},
	{"ID" : "5", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.read_phase_U0.grp_read_phase_Pipeline_VITIS_LOOP_30_1_fu_52.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_phase_U0.regslice_both_in_stream_V_data_V_U"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_phase_U0.regslice_both_in_stream_V_keep_V_U"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_phase_U0.regslice_both_in_stream_V_strb_V_U"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_phase_U0.regslice_both_in_stream_V_last_V_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.process_phase_U0"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38"},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38.mul_16s_13ns_29_1_1_U17"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38.mul_16s_12ns_28_1_1_U18"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38.mul_16s_13s_16_1_1_U19"},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38.mul_16s_13s_16_1_1_U20"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38.mac_muladd_16s_13s_26s_29_4_1_U21"},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38.mac_muladd_16s_13s_29s_29_4_1_U22"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38.mac_muladd_16s_13s_28s_29_4_1_U23"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.process_phase_U0.grp_process_phase_Pipeline_VITIS_LOOP_44_1_fu_38.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_phase_U0"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_phase_U0.flow_control_loop_pipe_U"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_phase_U0.regslice_both_out_stream_V_data_V_U"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_phase_U0.regslice_both_out_stream_V_keep_V_U"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_phase_U0.regslice_both_out_stream_V_strb_V_U"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_phase_U0.regslice_both_out_stream_V_last_V_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mode_c_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.coeff_stream_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.result_stream_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_process_phase_U0_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_write_phase_U0_U"}]}
set DependenceCheckSize 0
