-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snr_monitor_top is
generic (
    C_S_AXI_SNR_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_SNR_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    fft_in_0_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    fft_in_0_TVALID : IN STD_LOGIC;
    fft_in_0_TREADY : OUT STD_LOGIC;
    fft_in_0_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    fft_in_0_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    fft_in_0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    fft_in_1_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    fft_in_1_TVALID : IN STD_LOGIC;
    fft_in_1_TREADY : OUT STD_LOGIC;
    fft_in_1_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    fft_in_1_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    fft_in_1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    weight_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    weight_stream_TVALID : IN STD_LOGIC;
    weight_stream_TREADY : OUT STD_LOGIC;
    weight_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    weight_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    weight_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    symbol_num : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axi_SNR_AWVALID : IN STD_LOGIC;
    s_axi_SNR_AWREADY : OUT STD_LOGIC;
    s_axi_SNR_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_SNR_ADDR_WIDTH-1 downto 0);
    s_axi_SNR_WVALID : IN STD_LOGIC;
    s_axi_SNR_WREADY : OUT STD_LOGIC;
    s_axi_SNR_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_SNR_DATA_WIDTH-1 downto 0);
    s_axi_SNR_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_SNR_DATA_WIDTH/8-1 downto 0);
    s_axi_SNR_ARVALID : IN STD_LOGIC;
    s_axi_SNR_ARREADY : OUT STD_LOGIC;
    s_axi_SNR_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_SNR_ADDR_WIDTH-1 downto 0);
    s_axi_SNR_RVALID : OUT STD_LOGIC;
    s_axi_SNR_RREADY : IN STD_LOGIC;
    s_axi_SNR_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_SNR_DATA_WIDTH-1 downto 0);
    s_axi_SNR_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_SNR_BVALID : OUT STD_LOGIC;
    s_axi_SNR_BREADY : IN STD_LOGIC;
    s_axi_SNR_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of snr_monitor_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "snr_monitor_top_snr_monitor_top,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.380000,HLS_SYN_LAT=5204,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=1615,HLS_SYN_LUT=1960,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000001000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state50 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000010000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state51 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000100000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state52 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000001000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state53 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000010000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state54 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000100000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state55 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000001000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state56 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000010000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state57 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000100000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state58 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000001000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state59 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000010000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state60 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000100000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state61 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000001000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state62 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000010000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state63 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000100000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state64 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000001000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state65 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000010000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state66 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000100000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state67 : STD_LOGIC_VECTOR (77 downto 0) := "000000000001000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state68 : STD_LOGIC_VECTOR (77 downto 0) := "000000000010000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state69 : STD_LOGIC_VECTOR (77 downto 0) := "000000000100000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state70 : STD_LOGIC_VECTOR (77 downto 0) := "000000001000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state71 : STD_LOGIC_VECTOR (77 downto 0) := "000000010000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state72 : STD_LOGIC_VECTOR (77 downto 0) := "000000100000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state73 : STD_LOGIC_VECTOR (77 downto 0) := "000001000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state74 : STD_LOGIC_VECTOR (77 downto 0) := "000010000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state75 : STD_LOGIC_VECTOR (77 downto 0) := "000100000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state76 : STD_LOGIC_VECTOR (77 downto 0) := "001000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state77 : STD_LOGIC_VECTOR (77 downto 0) := "010000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state78 : STD_LOGIC_VECTOR (77 downto 0) := "100000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv39_1 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal snr_out_ap_vld : STD_LOGIC;
    signal icmp_ln113_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_285 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln168_1_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln168_1_reg_295 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal trunc_ln173_fu_269_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state77 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state77 : signal is "none";
    signal fft_re_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal fft_re_ce0 : STD_LOGIC;
    signal fft_re_we0 : STD_LOGIC;
    signal fft_re_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal fft_im_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal fft_im_ce0 : STD_LOGIC;
    signal fft_im_we0 : STD_LOGIC;
    signal fft_im_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal h_re_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal h_re_ce0 : STD_LOGIC;
    signal h_re_we0 : STD_LOGIC;
    signal h_re_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal h_im_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal h_im_ce0 : STD_LOGIC;
    signal h_im_we0 : STD_LOGIC;
    signal h_im_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_done : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_idle : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_ready : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_in_0_TREADY : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_ce0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_we0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_ce0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_we0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_in_1_TREADY : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_done : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_idle : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_ready : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_weight_stream_TREADY : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_ce0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_we0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_ce0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_we0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_done : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_idle : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_ready : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_re_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_re_ce0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_im_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_im_ce0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_re_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_re_ce0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_im_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_im_ce0 : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_nse_pow_out : STD_LOGIC_VECTOR (38 downto 0);
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_nse_pow_out_ap_vld : STD_LOGIC;
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_sig_pow_out : STD_LOGIC_VECTOR (38 downto 0);
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_sig_pow_out_ap_vld : STD_LOGIC;
    signal storemerge_reg_133 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln168_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state78 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state78 : signal is "none";
    signal sext_ln119_fu_207_p0 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln119_1_fu_211_p0 : STD_LOGIC_VECTOR (38 downto 0);
    signal trunc_ln168_fu_215_p0 : STD_LOGIC_VECTOR (38 downto 0);
    signal trunc_ln168_fu_215_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_shl_fu_219_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln119_1_fu_211_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln119_fu_207_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sub_ln168_fu_227_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal icmp_ln168_fu_239_p0 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln168_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal numerator_fu_249_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal numerator_fu_249_p3 : STD_LOGIC_VECTOR (54 downto 0);
    signal zext_ln173_fu_260_p0 : STD_LOGIC_VECTOR (38 downto 0);
    signal grp_fu_263_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_263_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal grp_fu_263_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_263_ap_start : STD_LOGIC;
    signal grp_fu_263_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (77 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ST_fsm_state39_blk : STD_LOGIC;
    signal ap_ST_fsm_state40_blk : STD_LOGIC;
    signal ap_ST_fsm_state41_blk : STD_LOGIC;
    signal ap_ST_fsm_state42_blk : STD_LOGIC;
    signal ap_ST_fsm_state43_blk : STD_LOGIC;
    signal ap_ST_fsm_state44_blk : STD_LOGIC;
    signal ap_ST_fsm_state45_blk : STD_LOGIC;
    signal ap_ST_fsm_state46_blk : STD_LOGIC;
    signal ap_ST_fsm_state47_blk : STD_LOGIC;
    signal ap_ST_fsm_state48_blk : STD_LOGIC;
    signal ap_ST_fsm_state49_blk : STD_LOGIC;
    signal ap_ST_fsm_state50_blk : STD_LOGIC;
    signal ap_ST_fsm_state51_blk : STD_LOGIC;
    signal ap_ST_fsm_state52_blk : STD_LOGIC;
    signal ap_ST_fsm_state53_blk : STD_LOGIC;
    signal ap_ST_fsm_state54_blk : STD_LOGIC;
    signal ap_ST_fsm_state55_blk : STD_LOGIC;
    signal ap_ST_fsm_state56_blk : STD_LOGIC;
    signal ap_ST_fsm_state57_blk : STD_LOGIC;
    signal ap_ST_fsm_state58_blk : STD_LOGIC;
    signal ap_ST_fsm_state59_blk : STD_LOGIC;
    signal ap_ST_fsm_state60_blk : STD_LOGIC;
    signal ap_ST_fsm_state61_blk : STD_LOGIC;
    signal ap_ST_fsm_state62_blk : STD_LOGIC;
    signal ap_ST_fsm_state63_blk : STD_LOGIC;
    signal ap_ST_fsm_state64_blk : STD_LOGIC;
    signal ap_ST_fsm_state65_blk : STD_LOGIC;
    signal ap_ST_fsm_state66_blk : STD_LOGIC;
    signal ap_ST_fsm_state67_blk : STD_LOGIC;
    signal ap_ST_fsm_state68_blk : STD_LOGIC;
    signal ap_ST_fsm_state69_blk : STD_LOGIC;
    signal ap_ST_fsm_state70_blk : STD_LOGIC;
    signal ap_ST_fsm_state71_blk : STD_LOGIC;
    signal ap_ST_fsm_state72_blk : STD_LOGIC;
    signal ap_ST_fsm_state73_blk : STD_LOGIC;
    signal ap_ST_fsm_state74_blk : STD_LOGIC;
    signal ap_ST_fsm_state75_blk : STD_LOGIC;
    signal ap_ST_fsm_state76_blk : STD_LOGIC;
    signal ap_ST_fsm_state77_blk : STD_LOGIC;
    signal ap_ST_fsm_state78_blk : STD_LOGIC;
    signal regslice_both_fft_in_0_V_data_V_U_apdone_blk : STD_LOGIC;
    signal fft_in_0_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_in_0_TVALID_int_regslice : STD_LOGIC;
    signal fft_in_0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_fft_in_0_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_fft_in_0_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal fft_in_0_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_fft_in_0_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fft_in_0_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_fft_in_0_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal fft_in_0_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_fft_in_0_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fft_in_0_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_fft_in_0_V_last_V_U_apdone_blk : STD_LOGIC;
    signal fft_in_0_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_fft_in_0_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fft_in_0_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_fft_in_1_V_data_V_U_apdone_blk : STD_LOGIC;
    signal fft_in_1_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_in_1_TVALID_int_regslice : STD_LOGIC;
    signal fft_in_1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_fft_in_1_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_fft_in_1_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal fft_in_1_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_fft_in_1_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fft_in_1_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_fft_in_1_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal fft_in_1_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_fft_in_1_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fft_in_1_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_fft_in_1_V_last_V_U_apdone_blk : STD_LOGIC;
    signal fft_in_1_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_fft_in_1_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fft_in_1_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_weight_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal weight_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal weight_stream_TVALID_int_regslice : STD_LOGIC;
    signal weight_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_weight_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_weight_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal weight_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_weight_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_weight_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_weight_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal weight_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_weight_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_weight_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_weight_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal weight_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_weight_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_weight_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal grp_fu_263_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component snr_monitor_top_snr_monitor_top_Pipeline_buf_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fft_in_0_TVALID : IN STD_LOGIC;
        fft_in_1_TVALID : IN STD_LOGIC;
        fft_in_0_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        fft_in_0_TREADY : OUT STD_LOGIC;
        fft_in_0_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        fft_in_0_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        fft_in_0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        fft_re_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        fft_re_ce0 : OUT STD_LOGIC;
        fft_re_we0 : OUT STD_LOGIC;
        fft_re_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        fft_im_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        fft_im_ce0 : OUT STD_LOGIC;
        fft_im_we0 : OUT STD_LOGIC;
        fft_im_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        fft_in_1_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        fft_in_1_TREADY : OUT STD_LOGIC;
        fft_in_1_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        fft_in_1_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        fft_in_1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component snr_monitor_top_snr_monitor_top_Pipeline_weight_drain IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        weight_stream_TVALID : IN STD_LOGIC;
        weight_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        weight_stream_TREADY : OUT STD_LOGIC;
        weight_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        weight_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        weight_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        h_re_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        h_re_ce0 : OUT STD_LOGIC;
        h_re_we0 : OUT STD_LOGIC;
        h_re_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        h_im_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        h_im_ce0 : OUT STD_LOGIC;
        h_im_we0 : OUT STD_LOGIC;
        h_im_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component snr_monitor_top_snr_monitor_top_Pipeline_pilot_snr IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fft_re_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        fft_re_ce0 : OUT STD_LOGIC;
        fft_re_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        fft_im_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        fft_im_ce0 : OUT STD_LOGIC;
        fft_im_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        h_re_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        h_re_ce0 : OUT STD_LOGIC;
        h_re_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        h_im_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        h_im_ce0 : OUT STD_LOGIC;
        h_im_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        nse_pow_out : OUT STD_LOGIC_VECTOR (38 downto 0);
        nse_pow_out_ap_vld : OUT STD_LOGIC;
        sig_pow_out : OUT STD_LOGIC_VECTOR (38 downto 0);
        sig_pow_out_ap_vld : OUT STD_LOGIC );
    end component;


    component snr_monitor_top_udiv_64s_39ns_32_68_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (38 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component snr_monitor_top_fft_re_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component snr_monitor_top_SNR_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        snr_out : IN STD_LOGIC_VECTOR (31 downto 0);
        snr_out_ap_vld : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component snr_monitor_top_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    fft_re_U : component snr_monitor_top_fft_re_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => fft_re_address0,
        ce0 => fft_re_ce0,
        we0 => fft_re_we0,
        d0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_d0,
        q0 => fft_re_q0);

    fft_im_U : component snr_monitor_top_fft_re_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => fft_im_address0,
        ce0 => fft_im_ce0,
        we0 => fft_im_we0,
        d0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_d0,
        q0 => fft_im_q0);

    h_re_U : component snr_monitor_top_fft_re_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => h_re_address0,
        ce0 => h_re_ce0,
        we0 => h_re_we0,
        d0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_d0,
        q0 => h_re_q0);

    h_im_U : component snr_monitor_top_fft_re_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => h_im_address0,
        ce0 => h_im_ce0,
        we0 => h_im_we0,
        d0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_d0,
        q0 => h_im_q0);

    grp_snr_monitor_top_Pipeline_buf_loop_fu_145 : component snr_monitor_top_snr_monitor_top_Pipeline_buf_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start,
        ap_done => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_done,
        ap_idle => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_idle,
        ap_ready => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_ready,
        fft_in_0_TVALID => fft_in_0_TVALID_int_regslice,
        fft_in_1_TVALID => fft_in_1_TVALID_int_regslice,
        fft_in_0_TDATA => fft_in_0_TDATA_int_regslice,
        fft_in_0_TREADY => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_in_0_TREADY,
        fft_in_0_TKEEP => fft_in_0_TKEEP_int_regslice,
        fft_in_0_TSTRB => fft_in_0_TSTRB_int_regslice,
        fft_in_0_TLAST => fft_in_0_TLAST_int_regslice,
        fft_re_address0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_address0,
        fft_re_ce0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_ce0,
        fft_re_we0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_we0,
        fft_re_d0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_d0,
        fft_im_address0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_address0,
        fft_im_ce0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_ce0,
        fft_im_we0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_we0,
        fft_im_d0 => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_d0,
        fft_in_1_TDATA => fft_in_1_TDATA_int_regslice,
        fft_in_1_TREADY => grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_in_1_TREADY,
        fft_in_1_TKEEP => fft_in_1_TKEEP_int_regslice,
        fft_in_1_TSTRB => fft_in_1_TSTRB_int_regslice,
        fft_in_1_TLAST => fft_in_1_TLAST_int_regslice);

    grp_snr_monitor_top_Pipeline_weight_drain_fu_167 : component snr_monitor_top_snr_monitor_top_Pipeline_weight_drain
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start,
        ap_done => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_done,
        ap_idle => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_idle,
        ap_ready => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_ready,
        weight_stream_TVALID => weight_stream_TVALID_int_regslice,
        weight_stream_TDATA => weight_stream_TDATA_int_regslice,
        weight_stream_TREADY => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_weight_stream_TREADY,
        weight_stream_TKEEP => weight_stream_TKEEP_int_regslice,
        weight_stream_TSTRB => weight_stream_TSTRB_int_regslice,
        weight_stream_TLAST => weight_stream_TLAST_int_regslice,
        h_re_address0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_address0,
        h_re_ce0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_ce0,
        h_re_we0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_we0,
        h_re_d0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_d0,
        h_im_address0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_address0,
        h_im_ce0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_ce0,
        h_im_we0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_we0,
        h_im_d0 => grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_d0);

    grp_snr_monitor_top_Pipeline_pilot_snr_fu_181 : component snr_monitor_top_snr_monitor_top_Pipeline_pilot_snr
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start,
        ap_done => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_done,
        ap_idle => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_idle,
        ap_ready => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_ready,
        fft_re_address0 => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_re_address0,
        fft_re_ce0 => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_re_ce0,
        fft_re_q0 => fft_re_q0,
        fft_im_address0 => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_im_address0,
        fft_im_ce0 => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_im_ce0,
        fft_im_q0 => fft_im_q0,
        h_re_address0 => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_re_address0,
        h_re_ce0 => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_re_ce0,
        h_re_q0 => h_re_q0,
        h_im_address0 => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_im_address0,
        h_im_ce0 => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_im_ce0,
        h_im_q0 => h_im_q0,
        nse_pow_out => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_nse_pow_out,
        nse_pow_out_ap_vld => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_nse_pow_out_ap_vld,
        sig_pow_out => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_sig_pow_out,
        sig_pow_out_ap_vld => grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_sig_pow_out_ap_vld);

    SNR_s_axi_U : component snr_monitor_top_SNR_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_SNR_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_SNR_DATA_WIDTH)
    port map (
        AWVALID => s_axi_SNR_AWVALID,
        AWREADY => s_axi_SNR_AWREADY,
        AWADDR => s_axi_SNR_AWADDR,
        WVALID => s_axi_SNR_WVALID,
        WREADY => s_axi_SNR_WREADY,
        WDATA => s_axi_SNR_WDATA,
        WSTRB => s_axi_SNR_WSTRB,
        ARVALID => s_axi_SNR_ARVALID,
        ARREADY => s_axi_SNR_ARREADY,
        ARADDR => s_axi_SNR_ARADDR,
        RVALID => s_axi_SNR_RVALID,
        RREADY => s_axi_SNR_RREADY,
        RDATA => s_axi_SNR_RDATA,
        RRESP => s_axi_SNR_RRESP,
        BVALID => s_axi_SNR_BVALID,
        BREADY => s_axi_SNR_BREADY,
        BRESP => s_axi_SNR_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        snr_out => storemerge_reg_133,
        snr_out_ap_vld => snr_out_ap_vld,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    udiv_64s_39ns_32_68_seq_1_U38 : component snr_monitor_top_udiv_64s_39ns_32_68_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 68,
        din0_WIDTH => 64,
        din1_WIDTH => 39,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        start => grp_fu_263_ap_start,
        done => grp_fu_263_ap_done,
        din0 => grp_fu_263_p0,
        din1 => grp_fu_263_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_263_p2);

    regslice_both_fft_in_0_V_data_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fft_in_0_TDATA,
        vld_in => fft_in_0_TVALID,
        ack_in => regslice_both_fft_in_0_V_data_V_U_ack_in,
        data_out => fft_in_0_TDATA_int_regslice,
        vld_out => fft_in_0_TVALID_int_regslice,
        ack_out => fft_in_0_TREADY_int_regslice,
        apdone_blk => regslice_both_fft_in_0_V_data_V_U_apdone_blk);

    regslice_both_fft_in_0_V_keep_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fft_in_0_TKEEP,
        vld_in => fft_in_0_TVALID,
        ack_in => regslice_both_fft_in_0_V_keep_V_U_ack_in,
        data_out => fft_in_0_TKEEP_int_regslice,
        vld_out => regslice_both_fft_in_0_V_keep_V_U_vld_out,
        ack_out => fft_in_0_TREADY_int_regslice,
        apdone_blk => regslice_both_fft_in_0_V_keep_V_U_apdone_blk);

    regslice_both_fft_in_0_V_strb_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fft_in_0_TSTRB,
        vld_in => fft_in_0_TVALID,
        ack_in => regslice_both_fft_in_0_V_strb_V_U_ack_in,
        data_out => fft_in_0_TSTRB_int_regslice,
        vld_out => regslice_both_fft_in_0_V_strb_V_U_vld_out,
        ack_out => fft_in_0_TREADY_int_regslice,
        apdone_blk => regslice_both_fft_in_0_V_strb_V_U_apdone_blk);

    regslice_both_fft_in_0_V_last_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fft_in_0_TLAST,
        vld_in => fft_in_0_TVALID,
        ack_in => regslice_both_fft_in_0_V_last_V_U_ack_in,
        data_out => fft_in_0_TLAST_int_regslice,
        vld_out => regslice_both_fft_in_0_V_last_V_U_vld_out,
        ack_out => fft_in_0_TREADY_int_regslice,
        apdone_blk => regslice_both_fft_in_0_V_last_V_U_apdone_blk);

    regslice_both_fft_in_1_V_data_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fft_in_1_TDATA,
        vld_in => fft_in_1_TVALID,
        ack_in => regslice_both_fft_in_1_V_data_V_U_ack_in,
        data_out => fft_in_1_TDATA_int_regslice,
        vld_out => fft_in_1_TVALID_int_regslice,
        ack_out => fft_in_1_TREADY_int_regslice,
        apdone_blk => regslice_both_fft_in_1_V_data_V_U_apdone_blk);

    regslice_both_fft_in_1_V_keep_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fft_in_1_TKEEP,
        vld_in => fft_in_1_TVALID,
        ack_in => regslice_both_fft_in_1_V_keep_V_U_ack_in,
        data_out => fft_in_1_TKEEP_int_regslice,
        vld_out => regslice_both_fft_in_1_V_keep_V_U_vld_out,
        ack_out => fft_in_1_TREADY_int_regslice,
        apdone_blk => regslice_both_fft_in_1_V_keep_V_U_apdone_blk);

    regslice_both_fft_in_1_V_strb_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fft_in_1_TSTRB,
        vld_in => fft_in_1_TVALID,
        ack_in => regslice_both_fft_in_1_V_strb_V_U_ack_in,
        data_out => fft_in_1_TSTRB_int_regslice,
        vld_out => regslice_both_fft_in_1_V_strb_V_U_vld_out,
        ack_out => fft_in_1_TREADY_int_regslice,
        apdone_blk => regslice_both_fft_in_1_V_strb_V_U_apdone_blk);

    regslice_both_fft_in_1_V_last_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fft_in_1_TLAST,
        vld_in => fft_in_1_TVALID,
        ack_in => regslice_both_fft_in_1_V_last_V_U_ack_in,
        data_out => fft_in_1_TLAST_int_regslice,
        vld_out => regslice_both_fft_in_1_V_last_V_U_vld_out,
        ack_out => fft_in_1_TREADY_int_regslice,
        apdone_blk => regslice_both_fft_in_1_V_last_V_U_apdone_blk);

    regslice_both_weight_stream_V_data_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => weight_stream_TDATA,
        vld_in => weight_stream_TVALID,
        ack_in => regslice_both_weight_stream_V_data_V_U_ack_in,
        data_out => weight_stream_TDATA_int_regslice,
        vld_out => weight_stream_TVALID_int_regslice,
        ack_out => weight_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_weight_stream_V_data_V_U_apdone_blk);

    regslice_both_weight_stream_V_keep_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => weight_stream_TKEEP,
        vld_in => weight_stream_TVALID,
        ack_in => regslice_both_weight_stream_V_keep_V_U_ack_in,
        data_out => weight_stream_TKEEP_int_regslice,
        vld_out => regslice_both_weight_stream_V_keep_V_U_vld_out,
        ack_out => weight_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_weight_stream_V_keep_V_U_apdone_blk);

    regslice_both_weight_stream_V_strb_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => weight_stream_TSTRB,
        vld_in => weight_stream_TVALID,
        ack_in => regslice_both_weight_stream_V_strb_V_U_ack_in,
        data_out => weight_stream_TSTRB_int_regslice,
        vld_out => regslice_both_weight_stream_V_strb_V_U_vld_out,
        ack_out => weight_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_weight_stream_V_strb_V_U_apdone_blk);

    regslice_both_weight_stream_V_last_V_U : component snr_monitor_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => weight_stream_TLAST,
        vld_in => weight_stream_TVALID,
        ack_in => regslice_both_weight_stream_V_last_V_U_ack_in,
        data_out => weight_stream_TLAST_int_regslice,
        vld_out => regslice_both_weight_stream_V_last_V_U_vld_out,
        ack_out => weight_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_weight_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_ready = ap_const_logic_1)) then 
                    grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_ready = ap_const_logic_1)) then 
                    grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_ready = ap_const_logic_1)) then 
                    grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    storemerge_reg_133_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln168_fu_244_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                storemerge_reg_133 <= ap_const_lv32_FFFFFFFF;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state77)) then 
                storemerge_reg_133 <= trunc_ln173_fu_269_p1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln113_reg_285 <= icmp_ln113_fu_195_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                icmp_ln168_1_reg_295 <= icmp_ln168_1_fu_233_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln113_reg_285, ap_CS_fsm_state10, grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_done, grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_done, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_done, or_ln168_fu_244_p2, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln113_reg_285 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state78;
                elsif (((grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln113_reg_285 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((or_ln168_fu_244_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state78;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                ap_NS_fsm <= ap_ST_fsm_state48;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state50;
            when ap_ST_fsm_state50 => 
                ap_NS_fsm <= ap_ST_fsm_state51;
            when ap_ST_fsm_state51 => 
                ap_NS_fsm <= ap_ST_fsm_state52;
            when ap_ST_fsm_state52 => 
                ap_NS_fsm <= ap_ST_fsm_state53;
            when ap_ST_fsm_state53 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when ap_ST_fsm_state54 => 
                ap_NS_fsm <= ap_ST_fsm_state55;
            when ap_ST_fsm_state55 => 
                ap_NS_fsm <= ap_ST_fsm_state56;
            when ap_ST_fsm_state56 => 
                ap_NS_fsm <= ap_ST_fsm_state57;
            when ap_ST_fsm_state57 => 
                ap_NS_fsm <= ap_ST_fsm_state58;
            when ap_ST_fsm_state58 => 
                ap_NS_fsm <= ap_ST_fsm_state59;
            when ap_ST_fsm_state59 => 
                ap_NS_fsm <= ap_ST_fsm_state60;
            when ap_ST_fsm_state60 => 
                ap_NS_fsm <= ap_ST_fsm_state61;
            when ap_ST_fsm_state61 => 
                ap_NS_fsm <= ap_ST_fsm_state62;
            when ap_ST_fsm_state62 => 
                ap_NS_fsm <= ap_ST_fsm_state63;
            when ap_ST_fsm_state63 => 
                ap_NS_fsm <= ap_ST_fsm_state64;
            when ap_ST_fsm_state64 => 
                ap_NS_fsm <= ap_ST_fsm_state65;
            when ap_ST_fsm_state65 => 
                ap_NS_fsm <= ap_ST_fsm_state66;
            when ap_ST_fsm_state66 => 
                ap_NS_fsm <= ap_ST_fsm_state67;
            when ap_ST_fsm_state67 => 
                ap_NS_fsm <= ap_ST_fsm_state68;
            when ap_ST_fsm_state68 => 
                ap_NS_fsm <= ap_ST_fsm_state69;
            when ap_ST_fsm_state69 => 
                ap_NS_fsm <= ap_ST_fsm_state70;
            when ap_ST_fsm_state70 => 
                ap_NS_fsm <= ap_ST_fsm_state71;
            when ap_ST_fsm_state71 => 
                ap_NS_fsm <= ap_ST_fsm_state72;
            when ap_ST_fsm_state72 => 
                ap_NS_fsm <= ap_ST_fsm_state73;
            when ap_ST_fsm_state73 => 
                ap_NS_fsm <= ap_ST_fsm_state74;
            when ap_ST_fsm_state74 => 
                ap_NS_fsm <= ap_ST_fsm_state75;
            when ap_ST_fsm_state75 => 
                ap_NS_fsm <= ap_ST_fsm_state76;
            when ap_ST_fsm_state76 => 
                ap_NS_fsm <= ap_ST_fsm_state77;
            when ap_ST_fsm_state77 => 
                ap_NS_fsm <= ap_ST_fsm_state78;
            when ap_ST_fsm_state78 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state77 <= ap_CS_fsm(76);
    ap_CS_fsm_state78 <= ap_CS_fsm(77);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;
    ap_ST_fsm_state38_blk <= ap_const_logic_0;
    ap_ST_fsm_state39_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_done)
    begin
        if ((grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state40_blk <= ap_const_logic_0;
    ap_ST_fsm_state41_blk <= ap_const_logic_0;
    ap_ST_fsm_state42_blk <= ap_const_logic_0;
    ap_ST_fsm_state43_blk <= ap_const_logic_0;
    ap_ST_fsm_state44_blk <= ap_const_logic_0;
    ap_ST_fsm_state45_blk <= ap_const_logic_0;
    ap_ST_fsm_state46_blk <= ap_const_logic_0;
    ap_ST_fsm_state47_blk <= ap_const_logic_0;
    ap_ST_fsm_state48_blk <= ap_const_logic_0;
    ap_ST_fsm_state49_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state50_blk <= ap_const_logic_0;
    ap_ST_fsm_state51_blk <= ap_const_logic_0;
    ap_ST_fsm_state52_blk <= ap_const_logic_0;
    ap_ST_fsm_state53_blk <= ap_const_logic_0;
    ap_ST_fsm_state54_blk <= ap_const_logic_0;
    ap_ST_fsm_state55_blk <= ap_const_logic_0;
    ap_ST_fsm_state56_blk <= ap_const_logic_0;
    ap_ST_fsm_state57_blk <= ap_const_logic_0;
    ap_ST_fsm_state58_blk <= ap_const_logic_0;
    ap_ST_fsm_state59_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state60_blk <= ap_const_logic_0;
    ap_ST_fsm_state61_blk <= ap_const_logic_0;
    ap_ST_fsm_state62_blk <= ap_const_logic_0;
    ap_ST_fsm_state63_blk <= ap_const_logic_0;
    ap_ST_fsm_state64_blk <= ap_const_logic_0;
    ap_ST_fsm_state65_blk <= ap_const_logic_0;
    ap_ST_fsm_state66_blk <= ap_const_logic_0;
    ap_ST_fsm_state67_blk <= ap_const_logic_0;
    ap_ST_fsm_state68_blk <= ap_const_logic_0;
    ap_ST_fsm_state69_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_done)
    begin
        if ((grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state70_blk <= ap_const_logic_0;
    ap_ST_fsm_state71_blk <= ap_const_logic_0;
    ap_ST_fsm_state72_blk <= ap_const_logic_0;
    ap_ST_fsm_state73_blk <= ap_const_logic_0;
    ap_ST_fsm_state74_blk <= ap_const_logic_0;
    ap_ST_fsm_state75_blk <= ap_const_logic_0;
    ap_ST_fsm_state76_blk <= ap_const_logic_0;
    ap_ST_fsm_state77_blk <= ap_const_logic_0;
    ap_ST_fsm_state78_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_done)
    begin
        if ((grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state78)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state78)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state78)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state78)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    fft_im_address0_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_address0, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_im_address0, ap_CS_fsm_state3, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            fft_im_address0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_im_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fft_im_address0 <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_address0;
        else 
            fft_im_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    fft_im_ce0_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_ce0, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_im_ce0, ap_CS_fsm_state3, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            fft_im_ce0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_im_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fft_im_ce0 <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_ce0;
        else 
            fft_im_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    fft_im_we0_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fft_im_we0 <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_im_we0;
        else 
            fft_im_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fft_in_0_TREADY <= regslice_both_fft_in_0_V_data_V_U_ack_in;

    fft_in_0_TREADY_int_regslice_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_in_0_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fft_in_0_TREADY_int_regslice <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_in_0_TREADY;
        else 
            fft_in_0_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    fft_in_1_TREADY <= regslice_both_fft_in_1_V_data_V_U_ack_in;

    fft_in_1_TREADY_int_regslice_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_in_1_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fft_in_1_TREADY_int_regslice <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_in_1_TREADY;
        else 
            fft_in_1_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    fft_re_address0_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_address0, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_re_address0, ap_CS_fsm_state3, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            fft_re_address0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_re_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fft_re_address0 <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_address0;
        else 
            fft_re_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    fft_re_ce0_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_ce0, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_re_ce0, ap_CS_fsm_state3, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            fft_re_ce0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_fft_re_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fft_re_ce0 <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_ce0;
        else 
            fft_re_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    fft_re_we0_assign_proc : process(grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fft_re_we0 <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_fft_re_we0;
        else 
            fft_re_we0 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_263_ap_start_assign_proc : process(ap_CS_fsm_state10, or_ln168_fu_244_p2)
    begin
        if (((or_ln168_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            grp_fu_263_ap_start <= ap_const_logic_1;
        else 
            grp_fu_263_ap_start <= ap_const_logic_0;
        end if; 
    end process;

        grp_fu_263_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(numerator_fu_249_p3),64));

    grp_fu_263_p1 <= grp_fu_263_p10(39 - 1 downto 0);
    grp_fu_263_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln173_fu_260_p0),64));
    grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start <= grp_snr_monitor_top_Pipeline_buf_loop_fu_145_ap_start_reg;
    grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_ap_start_reg;
    grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start <= grp_snr_monitor_top_Pipeline_weight_drain_fu_167_ap_start_reg;

    h_im_address0_assign_proc : process(grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_address0, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_im_address0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            h_im_address0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_im_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            h_im_address0 <= grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_address0;
        else 
            h_im_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    h_im_ce0_assign_proc : process(grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_ce0, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_im_ce0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            h_im_ce0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_im_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            h_im_ce0 <= grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_ce0;
        else 
            h_im_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    h_im_we0_assign_proc : process(grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_we0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            h_im_we0 <= grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_im_we0;
        else 
            h_im_we0 <= ap_const_logic_0;
        end if; 
    end process;


    h_re_address0_assign_proc : process(grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_address0, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_re_address0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            h_re_address0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_re_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            h_re_address0 <= grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_address0;
        else 
            h_re_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    h_re_ce0_assign_proc : process(grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_ce0, grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_re_ce0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            h_re_ce0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_h_re_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            h_re_ce0 <= grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_ce0;
        else 
            h_re_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    h_re_we0_assign_proc : process(grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_we0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            h_re_we0 <= grp_snr_monitor_top_Pipeline_weight_drain_fu_167_h_re_we0;
        else 
            h_re_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln113_fu_195_p2 <= "1" when (symbol_num = ap_const_lv4_2) else "0";
    icmp_ln168_1_fu_233_p2 <= "1" when (signed(sext_ln119_fu_207_p1) > signed(sub_ln168_fu_227_p2)) else "0";
    icmp_ln168_fu_239_p0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_nse_pow_out;
    icmp_ln168_fu_239_p2 <= "1" when (signed(icmp_ln168_fu_239_p0) < signed(ap_const_lv39_1)) else "0";
    numerator_fu_249_p1 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_sig_pow_out;
    numerator_fu_249_p3 <= (numerator_fu_249_p1 & ap_const_lv16_0);
    or_ln168_fu_244_p2 <= (icmp_ln168_fu_239_p2 or icmp_ln168_1_reg_295);
    p_shl_fu_219_p3 <= (trunc_ln168_fu_215_p1 & ap_const_lv16_0);
    sext_ln119_1_fu_211_p0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_nse_pow_out;
        sext_ln119_1_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln119_1_fu_211_p0),48));

    sext_ln119_fu_207_p0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_sig_pow_out;
        sext_ln119_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln119_fu_207_p0),48));


    snr_out_ap_vld_assign_proc : process(icmp_ln113_reg_285, ap_CS_fsm_state78)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state78) and (icmp_ln113_reg_285 = ap_const_lv1_1))) then 
            snr_out_ap_vld <= ap_const_logic_1;
        else 
            snr_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln168_fu_227_p2 <= std_logic_vector(unsigned(p_shl_fu_219_p3) - unsigned(sext_ln119_1_fu_211_p1));
    trunc_ln168_fu_215_p0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_nse_pow_out;
    trunc_ln168_fu_215_p1 <= trunc_ln168_fu_215_p0(32 - 1 downto 0);
    trunc_ln173_fu_269_p1 <= grp_fu_263_p2(32 - 1 downto 0);
    weight_stream_TREADY <= regslice_both_weight_stream_V_data_V_U_ack_in;

    weight_stream_TREADY_int_regslice_assign_proc : process(grp_snr_monitor_top_Pipeline_weight_drain_fu_167_weight_stream_TREADY, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            weight_stream_TREADY_int_regslice <= grp_snr_monitor_top_Pipeline_weight_drain_fu_167_weight_stream_TREADY;
        else 
            weight_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln173_fu_260_p0 <= grp_snr_monitor_top_Pipeline_pilot_snr_fu_181_nse_pow_out;
end behav;
