// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module chan_est_top_chan_est_top_Pipeline_buf_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fft_in_0_TVALID,
        fft_in_1_TVALID,
        fft_im_1_address0,
        fft_im_1_ce0,
        fft_im_1_we0,
        fft_im_1_d0,
        fft_im_address0,
        fft_im_ce0,
        fft_im_we0,
        fft_im_d0,
        fft_re_1_address0,
        fft_re_1_ce0,
        fft_re_1_we0,
        fft_re_1_d0,
        fft_re_address0,
        fft_re_ce0,
        fft_re_we0,
        fft_re_d0,
        fft_in_0_TDATA,
        fft_in_0_TREADY,
        fft_in_0_TKEEP,
        fft_in_0_TSTRB,
        fft_in_0_TLAST,
        fft_in_1_TDATA,
        fft_in_1_TREADY,
        fft_in_1_TKEEP,
        fft_in_1_TSTRB,
        fft_in_1_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   fft_in_0_TVALID;
input   fft_in_1_TVALID;
output  [9:0] fft_im_1_address0;
output   fft_im_1_ce0;
output   fft_im_1_we0;
output  [15:0] fft_im_1_d0;
output  [9:0] fft_im_address0;
output   fft_im_ce0;
output   fft_im_we0;
output  [15:0] fft_im_d0;
output  [9:0] fft_re_1_address0;
output   fft_re_1_ce0;
output   fft_re_1_we0;
output  [15:0] fft_re_1_d0;
output  [9:0] fft_re_address0;
output   fft_re_ce0;
output   fft_re_we0;
output  [15:0] fft_re_d0;
input  [31:0] fft_in_0_TDATA;
output   fft_in_0_TREADY;
input  [3:0] fft_in_0_TKEEP;
input  [3:0] fft_in_0_TSTRB;
input  [0:0] fft_in_0_TLAST;
input  [31:0] fft_in_1_TDATA;
output   fft_in_1_TREADY;
input  [3:0] fft_in_1_TKEEP;
input  [3:0] fft_in_1_TSTRB;
input  [0:0] fft_in_1_TLAST;

reg ap_idle;
reg fft_in_0_TREADY;
reg fft_in_1_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln228_fu_160_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    fft_in_0_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    fft_in_1_TDATA_blk_n;
reg   [10:0] k_2_reg_227;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] trunc_ln233_fu_176_p1;
reg   [15:0] trunc_ln233_reg_235;
reg   [15:0] tmp_s_reg_240;
wire   [15:0] trunc_ln233_1_fu_194_p1;
reg   [15:0] trunc_ln233_1_reg_245;
reg   [15:0] tmp_1_reg_250;
wire   [63:0] zext_ln228_fu_213_p1;
reg   [10:0] k_fu_72;
wire   [10:0] add_ln228_fu_166_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_k_2;
reg    fft_re_we0_local;
reg    fft_re_ce0_local;
reg    fft_re_1_we0_local;
reg    fft_re_1_ce0_local;
reg    fft_im_we0_local;
reg    fft_im_ce0_local;
reg    fft_im_1_we0_local;
reg    fft_im_1_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 k_fu_72 = 11'd0;
#0 ap_done_reg = 1'b0;
end

chan_est_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln228_fu_160_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            k_fu_72 <= add_ln228_fu_166_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_72 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_2_reg_227 <= ap_sig_allocacmp_k_2;
        tmp_1_reg_250 <= {{fft_in_1_TDATA[31:16]}};
        tmp_s_reg_240 <= {{fft_in_0_TDATA[31:16]}};
        trunc_ln233_1_reg_245 <= trunc_ln233_1_fu_194_p1;
        trunc_ln233_reg_235 <= trunc_ln233_fu_176_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln228_fu_160_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_2 = 11'd0;
    end else begin
        ap_sig_allocacmp_k_2 = k_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_im_1_ce0_local = 1'b1;
    end else begin
        fft_im_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_im_1_we0_local = 1'b1;
    end else begin
        fft_im_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_im_ce0_local = 1'b1;
    end else begin
        fft_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_im_we0_local = 1'b1;
    end else begin
        fft_im_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln228_fu_160_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_in_0_TDATA_blk_n = fft_in_0_TVALID;
    end else begin
        fft_in_0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln228_fu_160_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_in_0_TREADY = 1'b1;
    end else begin
        fft_in_0_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln228_fu_160_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_in_1_TDATA_blk_n = fft_in_1_TVALID;
    end else begin
        fft_in_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln228_fu_160_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_in_1_TREADY = 1'b1;
    end else begin
        fft_in_1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_re_1_ce0_local = 1'b1;
    end else begin
        fft_re_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_re_1_we0_local = 1'b1;
    end else begin
        fft_re_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_re_ce0_local = 1'b1;
    end else begin
        fft_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fft_re_we0_local = 1'b1;
    end else begin
        fft_re_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln228_fu_166_p2 = (ap_sig_allocacmp_k_2 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (((fft_in_1_TVALID == 1'b0) & (icmp_ln228_fu_160_p2 == 1'd0)) | ((icmp_ln228_fu_160_p2 == 1'd0) & (fft_in_0_TVALID == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign fft_im_1_address0 = zext_ln228_fu_213_p1;

assign fft_im_1_ce0 = fft_im_1_ce0_local;

assign fft_im_1_d0 = tmp_1_reg_250;

assign fft_im_1_we0 = fft_im_1_we0_local;

assign fft_im_address0 = zext_ln228_fu_213_p1;

assign fft_im_ce0 = fft_im_ce0_local;

assign fft_im_d0 = tmp_s_reg_240;

assign fft_im_we0 = fft_im_we0_local;

assign fft_re_1_address0 = zext_ln228_fu_213_p1;

assign fft_re_1_ce0 = fft_re_1_ce0_local;

assign fft_re_1_d0 = trunc_ln233_1_reg_245;

assign fft_re_1_we0 = fft_re_1_we0_local;

assign fft_re_address0 = zext_ln228_fu_213_p1;

assign fft_re_ce0 = fft_re_ce0_local;

assign fft_re_d0 = trunc_ln233_reg_235;

assign fft_re_we0 = fft_re_we0_local;

assign icmp_ln228_fu_160_p2 = ((ap_sig_allocacmp_k_2 == 11'd1024) ? 1'b1 : 1'b0);

assign trunc_ln233_1_fu_194_p1 = fft_in_1_TDATA[15:0];

assign trunc_ln233_fu_176_p1 = fft_in_0_TDATA[15:0];

assign zext_ln228_fu_213_p1 = k_2_reg_227;

endmodule //chan_est_top_chan_est_top_Pipeline_buf_loop
